// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CookieManagerPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * One cookie **read back** from the store, mirroring the platform interface's `Cookie`.
 *
 * 🚨 **`isSessionOnly` is deliberately absent, and that is a wire finding.** The public `Cookie`
 * declares it, and the old Kotlin seeded it into every map:
 *
 * ```kotlin
 * "isSessionOnly" to null,
 * ```
 *
 * ...and then **never assigned it again, on either branch**. Measured by grep over the whole
 * module: that line is the only occurrence in the Kotlin source. So Android has always answered
 * `isSessionOnly: null` for every cookie ever returned. Carrying it would be one always-null key
 * per cookie, the same finding as §160's seven-fields-per-proxy-rule and §163's nine-per-credential.
 * The Dart side keeps passing `null` for it when rebuilding the public object, so nothing observable
 * changes.
 *
 * Everything else stays nullable because it genuinely can be absent: without
 * `WebViewFeature.GET_COOKIE_INFO` the platform hands back a bare `name=value` string and there is
 * nothing to parse the rest out of, so only [name] and [value] are ever populated on that path.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CookieData (
  /** Always present: parsed from the left of the first `=` in every branch. */
  val name: String,
  /**
   * Always present, and **empty rather than null** when the cookie has no value -- the old Kotlin
   * did `if (nameValue.size > 1) ... else ""`. RFC 6265 §4.1.1 permits an empty value, so this
   * is a real state, not a missing one.
   */
  val value: String,
  /**
   * Epoch milliseconds. Crosses as a Dart `int`, which Pigeon maps to Kotlin `Long` -- which is
   * exactly what the `Expires` parse (`Date.getTime()`) and the `Max-Age` arithmetic already
   * produce, so this direction needs no narrowing.
   */
  val expiresDate: Long? = null,
  val domain: String? = null,
  /**
   * The platform's own spelling (`Lax` / `Strict` / `None`), not the Dart enum: the Dart side
   * rebuilds `HTTPCookieSameSitePolicy` with `fromNativeValue`, as before.
   */
  val sameSite: String? = null,
  val isSecure: Boolean? = null,
  val isHttpOnly: Boolean? = null,
  val path: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CookieData {
      val name = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String
      val expiresDate = pigeonVar_list[2] as Long?
      val domain = pigeonVar_list[3] as String?
      val sameSite = pigeonVar_list[4] as String?
      val isSecure = pigeonVar_list[5] as Boolean?
      val isHttpOnly = pigeonVar_list[6] as Boolean?
      val path = pigeonVar_list[7] as String?
      return CookieData(name, value, expiresDate, domain, sameSite, isSecure, isHttpOnly, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      value,
      expiresDate,
      domain,
      sameSite,
      isSecure,
      isHttpOnly,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CookieData
    return CookieManagerPigeonUtils.deepEquals(this.name, other.name) && CookieManagerPigeonUtils.deepEquals(this.value, other.value) && CookieManagerPigeonUtils.deepEquals(this.expiresDate, other.expiresDate) && CookieManagerPigeonUtils.deepEquals(this.domain, other.domain) && CookieManagerPigeonUtils.deepEquals(this.sameSite, other.sameSite) && CookieManagerPigeonUtils.deepEquals(this.isSecure, other.isSecure) && CookieManagerPigeonUtils.deepEquals(this.isHttpOnly, other.isHttpOnly) && CookieManagerPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.name)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.value)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.expiresDate)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.domain)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.sameSite)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.isSecure)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.isHttpOnly)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "CookieData(name=$name, value=$value, expiresDate=$expiresDate, domain=$domain, sameSite=$sameSite, isSecure=$isSecure, isHttpOnly=$isHttpOnly, path=$path)"
  }
}

/**
 * One cookie **to write**, mirroring the platform interface's `CookieToSet`.
 *
 * 🚨 **This type is what makes the singular and plural writes provably one code path.** The
 * hand-written Dart carried a comment explaining that `setCookies` had to hand-build its per-cookie
 * map rather than use `CookieToSet.toMap()`, because the generated map sent `expiresDate` as an
 * `int` while the singular `setCookie` had always sent it as a **String** -- and that
 * "two spellings of one value on one channel is how a field ends up silently null on the platform
 * side". The fix was to keep both spellings identical by hand.
 *
 * One Pigeon type removes the hazard rather than managing it: both methods take this, so there is
 * exactly one spelling and the compiler enforces it. The hand-written `_cookieToSetChannelArgs`
 * helper goes with it.
 *
 * [expiresDate] is therefore now a typed `int` on the wire in both directions, and the
 * `toString()` / `toLong()` round trip through a decimal string is gone. Android-only: iOS has its
 * own channel and is untouched by this.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CookieToSetData (
  val url: String,
  val name: String,
  val value: String,
  /**
   * Non-null: the public API defaults it to `"/"`, so it is never absent by the time it reaches
   * the wire.
   */
  val path: String,
  val domain: String? = null,
  /** Epoch milliseconds; see [CookieData.expiresDate]. */
  val expiresDate: Long? = null,
  /**
   * Seconds. Dart `int` -> Kotlin **`Long`** (checklist item 4). It is only interpolated into the
   * `Max-Age=` attribute of a `Set-Cookie` string, so the Kotlin builder takes a `Long?` directly
   * rather than narrowing with `.toInt()`: a narrowing here would buy nothing and could only lose
   * information. (§162 hit the narrowing case because androidx demanded an `Int`; nothing does
   * here.)
   */
  val maxAge: Long? = null,
  val isSecure: Boolean? = null,
  val isHttpOnly: Boolean? = null,
  /** See [CookieData.sameSite]. */
  val sameSite: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CookieToSetData {
      val url = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val value = pigeonVar_list[2] as String
      val path = pigeonVar_list[3] as String
      val domain = pigeonVar_list[4] as String?
      val expiresDate = pigeonVar_list[5] as Long?
      val maxAge = pigeonVar_list[6] as Long?
      val isSecure = pigeonVar_list[7] as Boolean?
      val isHttpOnly = pigeonVar_list[8] as Boolean?
      val sameSite = pigeonVar_list[9] as String?
      return CookieToSetData(url, name, value, path, domain, expiresDate, maxAge, isSecure, isHttpOnly, sameSite)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      name,
      value,
      path,
      domain,
      expiresDate,
      maxAge,
      isSecure,
      isHttpOnly,
      sameSite,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CookieToSetData
    return CookieManagerPigeonUtils.deepEquals(this.url, other.url) && CookieManagerPigeonUtils.deepEquals(this.name, other.name) && CookieManagerPigeonUtils.deepEquals(this.value, other.value) && CookieManagerPigeonUtils.deepEquals(this.path, other.path) && CookieManagerPigeonUtils.deepEquals(this.domain, other.domain) && CookieManagerPigeonUtils.deepEquals(this.expiresDate, other.expiresDate) && CookieManagerPigeonUtils.deepEquals(this.maxAge, other.maxAge) && CookieManagerPigeonUtils.deepEquals(this.isSecure, other.isSecure) && CookieManagerPigeonUtils.deepEquals(this.isHttpOnly, other.isHttpOnly) && CookieManagerPigeonUtils.deepEquals(this.sameSite, other.sameSite)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.url)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.name)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.value)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.path)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.domain)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.expiresDate)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.maxAge)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.isSecure)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.isHttpOnly)
    result = 31 * result + CookieManagerPigeonUtils.deepHash(this.sameSite)
    return result
  }
  override fun toString(): String {
    return "CookieToSetData(url=$url, name=$name, value=$value, path=$path, domain=$domain, expiresDate=$expiresDate, maxAge=$maxAge, isSecure=$isSecure, isHttpOnly=$isHttpOnly, sameSite=$sameSite)"
  }
}
private open class CookieManagerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CookieData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CookieToSetData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CookieData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CookieToSetData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CookieManagerHostApi {
  /**
   * Writes one cookie, answering whether the platform accepted it.
   *
   * `@async`: `CookieManager.setCookie` reports the outcome through a `ValueCallback<Boolean>`,
   * and the reply is that callback's argument. Without `@async` Pigeon would generate a
   * synchronous host method and the answer would be sent before the platform had produced one --
   * §160's finding, where `await` resolved before the proxy was actually in effect.
   */
  fun setCookie(cookie: CookieToSetData, profileName: String?, callback: (Result<Boolean>) -> Unit)
  /**
   * Writes several cookies in one round trip, answering one bool per cookie **in the order given**.
   *
   * `@async` for the same reason as [setCookie], compounded: the Kotlin fills a fixed-size array by
   * index and replies only once the last callback has landed, because collecting by completion
   * order would scramble the mapping this return type promises.
   *
   * An empty list answers an empty list without touching the platform. That short-circuit lives on
   * the **Dart** side and is why `setCookies with an empty list is a no-op` survives a dead channel
   * (§166) -- it is a genuine negative control, not migration coverage.
   */
  fun setCookies(cookies: List<CookieToSetData>, profileName: String?, callback: (Result<List<Boolean>>) -> Unit)
  /**
   * Every cookie the store holds for [url].
   *
   * Synchronous: `CookieManager.getCookie` and `CookieManagerCompat.getCookieInfo` both return
   * directly. Answers an empty list when the store cannot be resolved, as before.
   */
  fun getCookies(url: String, profileName: String?): List<CookieData>
  /**
   * Deletes one cookie by writing it back expired (`Max-Age=-1`).
   *
   * `@async`: the expiring write goes through `setCookie`'s `ValueCallback`, and its argument is
   * the reply.
   */
  fun deleteCookie(url: String, name: String, domain: String?, path: String, profileName: String?, callback: (Result<Boolean>) -> Unit)
  /**
   * Deletes every cookie for [url] by expiring each one.
   *
   * 🚨 **Not `@async`, although it is the only sibling of [deleteCookie] that isn't.** It expires
   * each cookie with `manager.setCookie(url, value, null)` -- passing a **null** callback -- and
   * then answers `true` synchronously. So completion is not callback-signalled here and §162's
   * rule applies in its corrected form: `@async` iff *completion* is callback-signalled, not
   * merely if a callback appears nearby. Marking this `@async` would be harmless but would
   * misdescribe it; leaving [deleteCookie] synchronous would not be.
   *
   * Note the consequence, which predates this migration and is preserved: the `true` means "the
   * expiring writes were issued", not "they succeeded".
   */
  fun deleteCookies(url: String, domain: String?, path: String, profileName: String?): Boolean
  /** Empties the store. `@async` -- `removeAllCookies` is `ValueCallback`-completed. */
  fun deleteAllCookies(profileName: String?, callback: (Result<Boolean>) -> Unit)
  /** Removes only session cookies. `@async` -- `removeSessionCookies` is `ValueCallback`-completed. */
  fun removeSessionCookies(profileName: String?, callback: (Result<Boolean>) -> Unit)
  /**
   * Forces pending writes to disk.
   *
   * Synchronous: `CookieManager.flush()` returns void and blocks. The reply is a literal `true`,
   * which is what P0b.9 / §55 was about -- the pre-fix code returned without replying at all and
   * the Dart future never completed. A MethodChannel has no timeout; Pigeon makes that
   * unrepresentable.
   */
  fun flush(profileName: String?): Boolean
  /**
   * Whether the store holds any cookie at all, store-wide.
   *
   * 🚨 **`bool?`, and the null is load-bearing.** Null means the store could not be resolved;
   * `false` means it was read and is empty. Collapsing the two would tell a caller "no cookies"
   * about a store that may well hold some -- and a caller skipping a logout-time clear on that
   * basis would skip it wrongly. §167's `an unknown profile resolves to no store` pins this.
   */
  fun hasCookies(profileName: String?): Boolean?
  /**
   * Whether `file://` pages may use cookies.
   *
   * **Takes no `profileName`** -- unlike every other method here. `allowFileSchemeCookies` is a
   * *static* on the framework class, so there is no instance to scope. The Kotlin still resolves a
   * manager first, purely as a guard: the static throws if no WebView provider is installed, and
   * the resolver already turns that case into the same null this returns.
   *
   * `bool?` for that reason; see [hasCookies].
   */
  fun isFileSchemeCookiesAllowed(): Boolean?
  /**
   * The cookie master switch. Answers whether the switch was applied.
   *
   * Note this governs cookies flowing through the WebView's own traffic, **not** the app's
   * programmatic writes -- `setCookie` still succeeds with this off, measured on both platforms
   * and pinned by `accept cookie master switch`.
   */
  fun setAcceptCookie(accept: Boolean, profileName: String?): Boolean
  /**
   * Reads the master switch. `bool?`; see [hasCookies] -- "not accepting" and "could not read"
   * are different answers and the platform default is `true`, so `false` would be the more
   * misleading collapse of the two.
   */
  fun isAcceptCookieEnabled(profileName: String?): Boolean?

  companion object {
    /** The codec used by CookieManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CookieManagerPigeonCodec()
    }
    /** Sets up an instance of `CookieManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CookieManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.setCookie$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cookieArg = args[0] as CookieToSetData
            val profileNameArg = args[1] as String?
            api.setCookie(cookieArg, profileNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CookieManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CookieManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.setCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cookiesArg = args[0] as List<CookieToSetData>
            val profileNameArg = args[1] as String?
            api.setCookies(cookiesArg, profileNameArg) { result: Result<List<Boolean>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CookieManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CookieManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.getCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getCookies(urlArg, profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.deleteCookie$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val nameArg = args[1] as String
            val domainArg = args[2] as String?
            val pathArg = args[3] as String
            val profileNameArg = args[4] as String?
            api.deleteCookie(urlArg, nameArg, domainArg, pathArg, profileNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CookieManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CookieManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.deleteCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val domainArg = args[1] as String?
            val pathArg = args[2] as String
            val profileNameArg = args[3] as String?
            val wrapped: List<Any?> = try {
              listOf(api.deleteCookies(urlArg, domainArg, pathArg, profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.deleteAllCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            api.deleteAllCookies(profileNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CookieManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CookieManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.removeSessionCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            api.removeSessionCookies(profileNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CookieManagerPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CookieManagerPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.flush(profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.hasCookies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.hasCookies(profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.isFileSchemeCookiesAllowed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isFileSchemeCookiesAllowed())
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.setAcceptCookie$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val acceptArg = args[0] as Boolean
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setAcceptCookie(acceptArg, profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.CookieManagerHostApi.isAcceptCookieEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.isAcceptCookieEnabled(profileNameArg))
            } catch (exception: Throwable) {
              CookieManagerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
