// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CustomPathHandlerPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
}
private open class CustomPathHandlerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Implemented on the Dart side by a private forwarding class, one per path handler, suffixed by
 * its id.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class CustomPathHandlerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CustomPathHandlerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CustomPathHandlerPigeonCodec()
    }
  }
  /**
   * The response for [path], the part of the URL after the handler's prefix, with no query. Null
   * means "not handled": the request goes to the network.
   *
   * The answer is `WebResourceResponse.toMap()` (checklist item 5).
   */
  fun handle(pathArg: String, callback: (Result<Map<String?, Any?>?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_inappwebview_android.CustomPathHandlerFlutterApi.handle$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pathArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as Map<String?, Any?>?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(CustomPathHandlerPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
