// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ProcessGlobalConfigPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Mirrors the platform interface's `ProcessGlobalConfigDirectoryBasePaths`.
 *
 * **Both fields are non-null on purpose.** The platform-interface type declares them
 * non-nullable, but the Kotlin side stored them as `String?` and force-unwrapped with `!!` when
 * building the `File`s. That only ever worked because Dart could not send null; typing them
 * `required` here makes the guarantee the Kotlin code was already relying on an explicit part of
 * the wire contract.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProcessGlobalConfigDirectoryBasePathsData (
  val dataDirectoryBasePath: String,
  val cacheDirectoryBasePath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessGlobalConfigDirectoryBasePathsData {
      val dataDirectoryBasePath = pigeonVar_list[0] as String
      val cacheDirectoryBasePath = pigeonVar_list[1] as String
      return ProcessGlobalConfigDirectoryBasePathsData(dataDirectoryBasePath, cacheDirectoryBasePath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dataDirectoryBasePath,
      cacheDirectoryBasePath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessGlobalConfigDirectoryBasePathsData
    return ProcessGlobalConfigPigeonUtils.deepEquals(this.dataDirectoryBasePath, other.dataDirectoryBasePath) && ProcessGlobalConfigPigeonUtils.deepEquals(this.cacheDirectoryBasePath, other.cacheDirectoryBasePath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProcessGlobalConfigPigeonUtils.deepHash(this.dataDirectoryBasePath)
    result = 31 * result + ProcessGlobalConfigPigeonUtils.deepHash(this.cacheDirectoryBasePath)
    return result
  }
  override fun toString(): String {
    return "ProcessGlobalConfigDirectoryBasePathsData(dataDirectoryBasePath=$dataDirectoryBasePath, cacheDirectoryBasePath=$cacheDirectoryBasePath)"
  }
}

/**
 * Mirrors the platform interface's `ProcessGlobalConfigSettings`.
 *
 * Deliberately a separate type, for the same reason as `FindSessionData`: the
 * platform-interface version is the public API, so it cannot be Pigeon-generated without coupling
 * every platform to this schema.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProcessGlobalConfigSettingsData (
  /**
   * Null means "no suffix", which is not the same as the empty string — androidx rejects an
   * empty suffix. The hand-written channel expressed this by omitting the map key.
   */
  val dataDirectorySuffix: String? = null,
  val directoryBasePaths: ProcessGlobalConfigDirectoryBasePathsData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessGlobalConfigSettingsData {
      val dataDirectorySuffix = pigeonVar_list[0] as String?
      val directoryBasePaths = pigeonVar_list[1] as ProcessGlobalConfigDirectoryBasePathsData?
      return ProcessGlobalConfigSettingsData(dataDirectorySuffix, directoryBasePaths)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dataDirectorySuffix,
      directoryBasePaths,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessGlobalConfigSettingsData
    return ProcessGlobalConfigPigeonUtils.deepEquals(this.dataDirectorySuffix, other.dataDirectorySuffix) && ProcessGlobalConfigPigeonUtils.deepEquals(this.directoryBasePaths, other.directoryBasePaths)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProcessGlobalConfigPigeonUtils.deepHash(this.dataDirectorySuffix)
    result = 31 * result + ProcessGlobalConfigPigeonUtils.deepHash(this.directoryBasePaths)
    return result
  }
  override fun toString(): String {
    return "ProcessGlobalConfigSettingsData(dataDirectorySuffix=$dataDirectorySuffix, directoryBasePaths=$directoryBasePaths)"
  }
}
private open class ProcessGlobalConfigPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessGlobalConfigDirectoryBasePathsData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessGlobalConfigSettingsData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProcessGlobalConfigDirectoryBasePathsData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ProcessGlobalConfigSettingsData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProcessGlobalConfigHostApi {
  /**
   * Returns whether the config was applied.
   *
   * `false` means there was no activity to apply it against — the settings were silently not
   * applied. A thrown error means androidx rejected the config (most often: it had already been
   * applied once in this process, which it permits only once).
   *
   * The Dart side **discards this value**, because the platform interface declares
   * `Future<void> apply(...)`. Keeping the bool on the wire preserves the hand-written channel's
   * semantics exactly and keeps the no-activity case distinguishable from success for anyone who
   * later wants to surface it; collapsing it to `void` would throw that away silently.
   */
  fun apply(settings: ProcessGlobalConfigSettingsData): Boolean

  companion object {
    /** The codec used by ProcessGlobalConfigHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProcessGlobalConfigPigeonCodec()
    }
    /** Sets up an instance of `ProcessGlobalConfigHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProcessGlobalConfigHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProcessGlobalConfigHostApi.apply$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as ProcessGlobalConfigSettingsData
            val wrapped: List<Any?> = try {
              listOf(api.apply(settingsArg))
            } catch (exception: Throwable) {
              ProcessGlobalConfigPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
