// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ProfileStorePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * One custom request header, mirroring the platform interface's `CustomHeader` and
 * `androidx.webkit.CustomHeader` alike.
 *
 * **One type for both directions, deliberately.** The same shape goes in on [addCustomHeader] and
 * comes back out of [getCustomHeaders], so there is exactly one spelling of it on the wire and the
 * compiler enforces that they agree -- §168's reason for a single `CookieToSetData`, applied here
 * before a second spelling could appear rather than after.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CustomHeaderData (
  /** Matched **case-insensitively** by the platform. The casing first added is the casing sent. */
  val name: String,
  /**
   * Matched **case-sensitively** by the platform -- the asymmetry with [name] is why
   * [ProfileStoreHostApi.getCustomHeaders] picks an androidx overload rather than letting Dart
   * filter the full set.
   */
  val value: String,
  /**
   * A `Set<String>` on both public sides, a `List<String>` here because the wire has no set.
   * Never null: a header with no rules is useless but is a real, representable state, and
   * collapsing empty to null would read as "every origin" (pinned by
   * `an empty rule set survives rather than becoming null`).
   */
  val originRules: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CustomHeaderData {
      val name = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String
      val originRules = pigeonVar_list[2] as List<String>
      return CustomHeaderData(name, value, originRules)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      value,
      originRules,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CustomHeaderData
    return ProfileStorePigeonUtils.deepEquals(this.name, other.name) && ProfileStorePigeonUtils.deepEquals(this.value, other.value) && ProfileStorePigeonUtils.deepEquals(this.originRules, other.originRules)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProfileStorePigeonUtils.deepHash(this.name)
    result = 31 * result + ProfileStorePigeonUtils.deepHash(this.value)
    result = 31 * result + ProfileStorePigeonUtils.deepHash(this.originRules)
    return result
  }
  override fun toString(): String {
    return "CustomHeaderData(name=$name, value=$value, originRules=$originRules)"
  }
}
private open class ProfileStorePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CustomHeaderData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CustomHeaderData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProfileStoreHostApi {
  /**
   * Every profile that exists, including the default one.
   *
   * Answers an **empty list** when `MULTI_PROFILE` is unsupported, which is indistinguishable from
   * a device that genuinely has no profiles -- except that it cannot happen, because the default
   * profile is always listed. So the empty list is unambiguous in practice: it means the feature is
   * missing. Preserved from the hand-written channel.
   */
  fun getAllProfileNames(): List<String>
  /**
   * Creates the profile called [name] if needed, answering the name the platform actually gave it.
   *
   * 🚨 **`String?`, and the null is load-bearing.** Null means `MULTI_PROFILE` is unsupported and
   * *nothing was created*; it is not the same as a profile whose name is empty. Collapsing the two
   * would let a caller hand `""` to `InAppWebViewSettings.profileName` believing it had a profile.
   *
   * The name is read back off the returned `Profile` rather than echoing [name], so the reply
   * reflects what the platform created. That also means the reply is not free of consequence:
   * creating a profile **loads it into memory for the life of the process**, which is what makes
   * [deleteProfile] refuse it afterwards.
   */
  fun getOrCreateProfile(name: String): String?
  /**
   * Deletes the profile called [name].
   *
   * Answers `false` for "no such profile" and for "`MULTI_PROFILE` unsupported". It **throws** for
   * the two refusals, and that is the interesting part of this method.
   *
   * 🚨 **The Kotlin must throw `FlutterError("ProfileStoreManager", …)`, not let androidx's
   * exception propagate.** androidx raises two different classes -- `IllegalStateException` when a
   * living WebView holds the profile or the profile was loaded this run, `IllegalArgumentException`
   * when the name is the default profile -- and Pigeon's `wrapError` derives
   * `PlatformException.code` from `javaClass.simpleName` for anything that is not a `FlutterError`.
   * Letting them propagate would therefore replace one stable code with two exception-class names.
   *
   * That code is not incidental: §171 leaned on `PlatformException(code: "ProfileStoreManager",
   * "Cannot delete in-use profile")` as its example of a *clean* platform error, in contrast to the
   * `channel-error` a dead handler produces. `profile_store_delete.dart` pins it on a device, with
   * both refusals asserted so that the normalisation is observable rather than implied -- a single
   * refusal would report `"IllegalStateException"` under the broken version and look like a rename.
   *
   * Not `@async` despite throwing: see checklist item 2. Pigeon's synchronous wrapper is precisely
   * what carries the `FlutterError` into the error envelope.
   */
  fun deleteProfile(name: String): Boolean
  /**
   * Adds [header] to the profile named [profileName], or to the default profile when it is null.
   *
   * 🚨 **`void`, where the old channel answered a constant `true`.** The hand-written handler ran
   * `customHeaderProfile(call)?.addCustomHeader(...)` and then replied `true` unconditionally --
   * including when `CUSTOM_REQUEST_HEADERS` was missing, and when the named profile did not exist,
   * in which case the elvis swallowed the call and nothing was added. The Dart side declares
   * `Future<void>` and discarded that `true` anyway, so dropping it changes nothing observable and
   * stops the wire carrying a value that never meant anything.
   *
   * This is the mirror image of §169's finding on `web_storage_manager`, where the host computed a
   * meaningful answer that Dart threw away. Here the host threw away the meaning and Dart was
   * discarding the husk. Making it honestly answerable is a platform-interface change (`Future<bool>`
   * on five methods), not a transport one, and is filed rather than done here.
   */
  fun addCustomHeader(header: CustomHeaderData, profileName: String?)
  /**
   * Whether the profile carries any header called [headerName], matched case-insensitively.
   *
   * `bool`, not `bool?`: `false` here collapses "no such header" with "the profile or the feature
   * could not be resolved". That collapse predates this migration -- the Kotlin had `?: false` and
   * the Dart `?? false` -- and is preserved rather than fixed, because widening it is a change to
   * `PlatformProfileStore.hasCustomHeader`'s declared `Future<bool>`. Contrast `hasCookies` in
   * `cookie_manager.dart`, where §168 *did* have a `bool?` to preserve.
   */
  fun hasCustomHeader(headerName: String, profileName: String?): Boolean
  /**
   * The profile's headers, optionally filtered.
   *
   * The three androidx overloads collapse into one method with two optional arguments, and **the
   * Kotlin picks the overload** -- it does not filter a full set in Dart. That is not a style
   * preference: androidx matches [CustomHeaderData.name] case-insensitively and
   * [CustomHeaderData.value] case-sensitively, so a Dart-side `where` would get the mixed-case
   * cases wrong. A null [headerName] selects the unfiltered overload; a non-null [headerName] with
   * a null [headerValue] selects the name-only one.
   *
   * Answers an empty list when the profile or the feature could not be resolved.
   */
  fun getCustomHeaders(headerName: String?, headerValue: String?, profileName: String?): List<CustomHeaderData>
  /**
   * Removes headers called [headerName] -- every value under that name when [headerValue] is null,
   * otherwise only the one with that exact value.
   *
   * `void`; see [addCustomHeader] for why the old constant `true` is gone.
   */
  fun clearCustomHeader(headerName: String, headerValue: String?, profileName: String?)
  /** Removes every header from the profile. `void`; see [addCustomHeader]. */
  fun clearAllCustomHeaders(profileName: String?)

  companion object {
    /** The codec used by ProfileStoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProfileStorePigeonCodec()
    }
    /** Sets up an instance of `ProfileStoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProfileStoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getAllProfileNames$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAllProfileNames())
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getOrCreateProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getOrCreateProfile(nameArg))
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.deleteProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteProfile(nameArg))
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.addCustomHeader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headerArg = args[0] as CustomHeaderData
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.addCustomHeader(headerArg, profileNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.hasCustomHeader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headerNameArg = args[0] as String
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.hasCustomHeader(headerNameArg, profileNameArg))
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getCustomHeaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headerNameArg = args[0] as String?
            val headerValueArg = args[1] as String?
            val profileNameArg = args[2] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getCustomHeaders(headerNameArg, headerValueArg, profileNameArg))
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.clearCustomHeader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headerNameArg = args[0] as String
            val headerValueArg = args[1] as String?
            val profileNameArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.clearCustomHeader(headerNameArg, headerValueArg, profileNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.clearAllCustomHeaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.clearAllCustomHeaders(profileNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProfileStorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
