// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ProxyPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Mirrors the **Android-relevant half** of the platform interface's `ProxyRule`.
 *
 * `ProxyRule` declares **nine** fields, seven of which are iOS-only (`allowFailover`, `username`,
 * `password`, `excludedDomains`, `matchDomains`, `relayHop1`, `relayHop2`). Its generated
 * `toMap()` emits all nine unconditionally, so the hand-written channel this replaces sent seven
 * fields per rule that the Kotlin side never read.
 *
 * Worse, it could not have read them: `ProxySettings.parse` casts the incoming list to
 * `List<Map<String, String>>` and `ProxyRuleExt.fromMap` takes a `Map<String, String>`, while the
 * actual payload holds bools, lists and nested maps. That cast is **false at runtime** and
 * survives only because Kotlin erases generics — it would throw the moment anything iterated the
 * values as `String`. Naming just the two fields Android reads makes the wire honest and deletes
 * the cast along with the lie.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProxyRuleData (
  val url: String,
  /**
   * `ProxySchemeFilter`'s native value: `"*"`, `"http"` or `"https"`.
   *
   * Stays a `String` rather than becoming a Pigeon enum: androidx types this parameter as
   * `@ProxyConfig.ProxyScheme String`, and the platform interface's `ProxySchemeFilter` is an
   * open-ended `_internal(String)` class rather than a closed enum, so a generated enum here
   * would reject values the public API accepts.
   *
   * Null means "no scheme filter", which selects androidx's one-argument
   * `addProxyRule(url)` overload instead of `addProxyRule(url, schemeFilter)`.
   */
  val schemeFilter: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProxyRuleData {
      val url = pigeonVar_list[0] as String
      val schemeFilter = pigeonVar_list[1] as String?
      return ProxyRuleData(url, schemeFilter)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      schemeFilter,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProxyRuleData
    return ProxyPigeonUtils.deepEquals(this.url, other.url) && ProxyPigeonUtils.deepEquals(this.schemeFilter, other.schemeFilter)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProxyPigeonUtils.deepHash(this.url)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.schemeFilter)
    return result
  }
  override fun toString(): String {
    return "ProxyRuleData(url=$url, schemeFilter=$schemeFilter)"
  }
}

/**
 * Mirrors the platform interface's `ProxySettings`.
 *
 * Deliberately a separate type, for the same reason as `FindSessionData` and
 * `ProcessGlobalConfigSettingsData`: the platform-interface version is the public API and is
 * shared with iOS, so it cannot be Pigeon-generated without coupling every platform to this
 * schema.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProxySettingsData (
  val bypassRules: List<String>,
  val directs: List<String>,
  val proxyRules: List<ProxyRuleData>,
  /**
   * **Non-null on purpose.** The platform interface declares `bool reverseBypassEnabled` with a
   * default of `false`, so Dart can never send null — but the Kotlin side stored it as `Boolean?`
   * and gated the androidx call on `reverseBypassEnabled != null && isFeatureSupported(...)`.
   * That null check could never fail, so typing it `required` here changes no behaviour and makes
   * the guarantee the Kotlin code already relied on part of the wire contract. Same situation as
   * `ProcessGlobalConfigDirectoryBasePathsData`'s two paths (§157).
   */
  val reverseBypassEnabled: Boolean,
  /**
   * Tri-state, and the third state matters: androidx's `bypassSimpleHostnames()` is a *builder
   * call*, not a setter, so there is no way to ask for "off". Null and `false` both mean "do not
   * call it" and only `true` invokes it. The hand-written channel expressed this as a
   * `== true` comparison; keeping the field nullable preserves it exactly.
   */
  val bypassSimpleHostnames: Boolean? = null,
  /**
   * Tri-state for the same reason as [bypassSimpleHostnames] — `removeImplicitRules()` is also a
   * builder call with no inverse.
   */
  val removeImplicitRules: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProxySettingsData {
      val bypassRules = pigeonVar_list[0] as List<String>
      val directs = pigeonVar_list[1] as List<String>
      val proxyRules = pigeonVar_list[2] as List<ProxyRuleData>
      val reverseBypassEnabled = pigeonVar_list[3] as Boolean
      val bypassSimpleHostnames = pigeonVar_list[4] as Boolean?
      val removeImplicitRules = pigeonVar_list[5] as Boolean?
      return ProxySettingsData(bypassRules, directs, proxyRules, reverseBypassEnabled, bypassSimpleHostnames, removeImplicitRules)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bypassRules,
      directs,
      proxyRules,
      reverseBypassEnabled,
      bypassSimpleHostnames,
      removeImplicitRules,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProxySettingsData
    return ProxyPigeonUtils.deepEquals(this.bypassRules, other.bypassRules) && ProxyPigeonUtils.deepEquals(this.directs, other.directs) && ProxyPigeonUtils.deepEquals(this.proxyRules, other.proxyRules) && ProxyPigeonUtils.deepEquals(this.reverseBypassEnabled, other.reverseBypassEnabled) && ProxyPigeonUtils.deepEquals(this.bypassSimpleHostnames, other.bypassSimpleHostnames) && ProxyPigeonUtils.deepEquals(this.removeImplicitRules, other.removeImplicitRules)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProxyPigeonUtils.deepHash(this.bypassRules)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.directs)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.proxyRules)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.reverseBypassEnabled)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.bypassSimpleHostnames)
    result = 31 * result + ProxyPigeonUtils.deepHash(this.removeImplicitRules)
    return result
  }
  override fun toString(): String {
    return "ProxySettingsData(bypassRules=$bypassRules, directs=$directs, proxyRules=$proxyRules, reverseBypassEnabled=$reverseBypassEnabled, bypassSimpleHostnames=$bypassSimpleHostnames, removeImplicitRules=$removeImplicitRules)"
  }
}
private open class ProxyPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProxyRuleData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProxySettingsData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProxyRuleData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ProxySettingsData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProxyHostApi {
  /**
   * **`@async` is load-bearing, not a style choice.**
   *
   * androidx's `ProxyController.setProxyOverride` takes an `Executor` and a completion
   * `Runnable`; the hand-written channel called `result.success(true)` from *inside* that
   * callback. Without `@async` Pigeon emits `fun setProxyOverride(...): Boolean`, which must
   * return before the callback can possibly have run — so `await` would resolve while the proxy
   * was not yet in effect. That is a silent behaviour change and the reason this pair is
   * annotated: `@async` gives Kotlin a `(Result<Boolean>) -> Unit` callback to hand the
   * completion to.
   *
   * Returns whether the override was applied.
   *
   * `false` means androidx does not support `PROXY_OVERRIDE` on this WebView, so there was no
   * `ProxyController` to apply the settings to and they were silently dropped.
   *
   * The Dart side **discards this value**, because the platform interface declares
   * `Future<void> setProxyOverride(...)`. Keeping the bool on the wire preserves the hand-written
   * channel's semantics exactly and keeps the unsupported case distinguishable from success for
   * anyone who later wants to surface it; collapsing it to `void` would throw that away
   * silently. Same call as `ProcessGlobalConfigHostApi.apply` (§157).
   *
   * Completion is **asynchronous on the platform side**: androidx takes an `Executor` and a
   * callback, and this only returns once that callback has run, so awaiting it means the proxy is
   * actually in effect.
   */
  fun setProxyOverride(settings: ProxySettingsData, callback: (Result<Boolean>) -> Unit)
  /**
   * Returns whether the override was cleared, with `false` carrying the same
   * "`PROXY_OVERRIDE` unsupported" meaning as [setProxyOverride], and likewise discarded by Dart.
   *
   * `@async` for the same reason as [setProxyOverride] — `clearProxyOverride` is also
   * executor-plus-callback on the androidx side.
   */
  fun clearProxyOverride(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by ProxyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProxyPigeonCodec()
    }
    /** Sets up an instance of `ProxyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProxyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProxyHostApi.setProxyOverride$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as ProxySettingsData
            api.setProxyOverride(settingsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProxyPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProxyPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ProxyHostApi.clearProxyOverride$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearProxyOverride{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProxyPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProxyPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
