// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PullToRefreshPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}
private open class PullToRefreshPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Every setter answers `false` when the layout has already been disposed and `true` otherwise.
 * The Dart side has never bound that value (checklist item 9).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PullToRefreshHostApi {
  fun setEnabled(enabled: Boolean): Boolean
  /** `false` also when the layout has gone away — indistinguishable from "disabled", as before. */
  fun isEnabled(): Boolean
  /**
   * Backs both `beginRefreshing` (`true`) and `endRefreshing` (`false`). Moving the indicator
   * this way does **not** fire `onRefresh`; §181 pins that.
   */
  fun setRefreshing(refreshing: Boolean): Boolean
  fun isRefreshing(): Boolean
  /** A `#AARRGGBB` string, parsed by `Color.parseColor` on the platform side exactly as before. */
  fun setColor(color: String): Boolean
  /** See [setColor]. */
  fun setBackgroundColor(color: String): Boolean
  fun setDistanceToTriggerSync(distanceToTriggerSync: Long): Boolean
  fun setSlingshotDistance(slingshotDistance: Long): Boolean
  /**
   * `SwipeRefreshLayout.DEFAULT_SLINGSHOT_DISTANCE`, which is **-1** — a sentinel meaning "compute
   * the default", not a distance (§181, read out of the AAR).
   */
  fun getDefaultSlingshotDistance(): Long
  /**
   * The native `SwipeRefreshLayout` size constant: `LARGE = 0`, `DEFAULT = 1`. Narrowed into an
   * `@IntDef` on the platform side (checklist item 4).
   */
  fun setSize(size: Long): Boolean

  companion object {
    /** The codec used by PullToRefreshHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PullToRefreshPigeonCodec()
    }
    /** Sets up an instance of `PullToRefreshHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PullToRefreshHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.setEnabled(enabledArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.isEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isEnabled())
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setRefreshing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val refreshingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.setRefreshing(refreshingArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.isRefreshing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isRefreshing())
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setColor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val colorArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.setColor(colorArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setBackgroundColor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val colorArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.setBackgroundColor(colorArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setDistanceToTriggerSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val distanceToTriggerSyncArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.setDistanceToTriggerSync(distanceToTriggerSyncArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setSlingshotDistance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val slingshotDistanceArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.setSlingshotDistance(slingshotDistanceArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.getDefaultSlingshotDistance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDefaultSlingshotDistance())
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshHostApi.setSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sizeArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.setSize(sizeArg))
            } catch (exception: Throwable) {
              PullToRefreshPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PullToRefreshFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PullToRefreshFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PullToRefreshPigeonCodec()
    }
  }
  /** The user pulled far enough to trigger a refresh. Never fired by `setRefreshing`. */
  fun onRefresh(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_inappwebview_android.PullToRefreshFlutterApi.onRefresh$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PullToRefreshPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
