// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.nosferatu500.inappwebview.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ServiceWorkerPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Mirrors the native `WebResourceRequestExt` field for field (checklist item 5).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WebResourceRequestData (
  val url: String,
  val headers: Map<String, String>? = null,
  val isRedirect: Boolean,
  val hasGesture: Boolean,
  val isForMainFrame: Boolean,
  val method: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WebResourceRequestData {
      val url = pigeonVar_list[0] as String
      val headers = pigeonVar_list[1] as Map<String, String>?
      val isRedirect = pigeonVar_list[2] as Boolean
      val hasGesture = pigeonVar_list[3] as Boolean
      val isForMainFrame = pigeonVar_list[4] as Boolean
      val method = pigeonVar_list[5] as String?
      return WebResourceRequestData(url, headers, isRedirect, hasGesture, isForMainFrame, method)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      headers,
      isRedirect,
      hasGesture,
      isForMainFrame,
      method,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WebResourceRequestData
    return ServiceWorkerPigeonUtils.deepEquals(this.url, other.url) && ServiceWorkerPigeonUtils.deepEquals(this.headers, other.headers) && ServiceWorkerPigeonUtils.deepEquals(this.isRedirect, other.isRedirect) && ServiceWorkerPigeonUtils.deepEquals(this.hasGesture, other.hasGesture) && ServiceWorkerPigeonUtils.deepEquals(this.isForMainFrame, other.isForMainFrame) && ServiceWorkerPigeonUtils.deepEquals(this.method, other.method)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.url)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.headers)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.isRedirect)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.hasGesture)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.isForMainFrame)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.method)
    return result
  }
  override fun toString(): String {
    return "WebResourceRequestData(url=$url, headers=$headers, isRedirect=$isRedirect, hasGesture=$hasGesture, isForMainFrame=$isForMainFrame, method=$method)"
  }
}

/**
 * Mirrors the native `WebResourceResponseExt` field for field (checklist item 5).
 *
 * Every field is nullable because every field of the public `WebResourceResponse` is, and
 * `WebResourceResponseExt.toWebResourceResponse` branches on which ones are present: a missing
 * `statusCode` or `reasonPhrase` selects the three-argument framework constructor, and non-empty
 * `cookies` select the compat path. Defaulting any of them here would change that choice.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WebResourceResponseData (
  val contentType: String? = null,
  val contentEncoding: String? = null,
  val statusCode: Long? = null,
  val reasonPhrase: String? = null,
  val headers: Map<String, String>? = null,
  val data: ByteArray? = null,
  val cookies: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WebResourceResponseData {
      val contentType = pigeonVar_list[0] as String?
      val contentEncoding = pigeonVar_list[1] as String?
      val statusCode = pigeonVar_list[2] as Long?
      val reasonPhrase = pigeonVar_list[3] as String?
      val headers = pigeonVar_list[4] as Map<String, String>?
      val data = pigeonVar_list[5] as ByteArray?
      val cookies = pigeonVar_list[6] as List<String>?
      return WebResourceResponseData(contentType, contentEncoding, statusCode, reasonPhrase, headers, data, cookies)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentType,
      contentEncoding,
      statusCode,
      reasonPhrase,
      headers,
      data,
      cookies,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WebResourceResponseData
    return ServiceWorkerPigeonUtils.deepEquals(this.contentType, other.contentType) && ServiceWorkerPigeonUtils.deepEquals(this.contentEncoding, other.contentEncoding) && ServiceWorkerPigeonUtils.deepEquals(this.statusCode, other.statusCode) && ServiceWorkerPigeonUtils.deepEquals(this.reasonPhrase, other.reasonPhrase) && ServiceWorkerPigeonUtils.deepEquals(this.headers, other.headers) && ServiceWorkerPigeonUtils.deepEquals(this.data, other.data) && ServiceWorkerPigeonUtils.deepEquals(this.cookies, other.cookies)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.contentType)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.contentEncoding)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.statusCode)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.reasonPhrase)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.headers)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.data)
    result = 31 * result + ServiceWorkerPigeonUtils.deepHash(this.cookies)
    return result
  }
  override fun toString(): String {
    return "WebResourceResponseData(contentType=$contentType, contentEncoding=$contentEncoding, statusCode=$statusCode, reasonPhrase=$reasonPhrase, headers=$headers, data=${data?.contentToString()}, cookies=$cookies)"
  }
}
private open class ServiceWorkerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WebResourceRequestData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WebResourceResponseData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WebResourceRequestData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is WebResourceResponseData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Every method but [setServiceWorkerClient] takes a `profileName`: null is the default profile
 * (androidx `ServiceWorkerWebSettingsCompat`), a name is that profile's framework
 * `ServiceWorkerWebSettings`. [setServiceWorkerClient] deliberately takes none — the intercept event
 * carries no profile identity, so a per-profile client could not be told apart in Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ServiceWorkerHostApi {
  /** `false` only when the native manager has gone away. */
  fun setServiceWorkerClient(isNull: Boolean): Boolean
  /** `false` also when the settings are unreachable, as before — unlike the cookie-intercept getter. */
  fun getAllowContentAccess(profileName: String?): Boolean
  fun getAllowFileAccess(profileName: String?): Boolean
  fun getBlockNetworkLoads(profileName: String?): Boolean
  fun getCacheMode(profileName: String?): Long?
  /**
   * **Nullable, and must stay so**: null is a real answer (feature unsupported, or a named profile,
   * whose framework settings have no such API). §126 depends on the three states staying apart.
   */
  fun getIncludeCookiesOnShouldInterceptRequestEnabled(profileName: String?): Boolean?
  fun setAllowContentAccess(allow: Boolean, profileName: String?): Boolean
  fun setAllowFileAccess(allow: Boolean, profileName: String?): Boolean
  fun setBlockNetworkLoads(flag: Boolean, profileName: String?): Boolean
  /** A native `WebSettings` cache-mode constant, narrowed into an `@IntDef` (checklist item 4). */
  fun setCacheMode(mode: Long, profileName: String?): Boolean
  fun setIncludeCookiesOnShouldInterceptRequestEnabled(enabled: Boolean, profileName: String?): Boolean

  companion object {
    /** The codec used by ServiceWorkerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ServiceWorkerPigeonCodec()
    }
    /** Sets up an instance of `ServiceWorkerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceWorkerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setServiceWorkerClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isNullArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.setServiceWorkerClient(isNullArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.getAllowContentAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getAllowContentAccess(profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.getAllowFileAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getAllowFileAccess(profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.getBlockNetworkLoads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getBlockNetworkLoads(profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.getCacheMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getCacheMode(profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.getIncludeCookiesOnShouldInterceptRequestEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileNameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getIncludeCookiesOnShouldInterceptRequestEnabled(profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setAllowContentAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val allowArg = args[0] as Boolean
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setAllowContentAccess(allowArg, profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setAllowFileAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val allowArg = args[0] as Boolean
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setAllowFileAccess(allowArg, profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setBlockNetworkLoads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flagArg = args[0] as Boolean
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setBlockNetworkLoads(flagArg, profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setCacheMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as Long
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setCacheMode(modeArg, profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerHostApi.setIncludeCookiesOnShouldInterceptRequestEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val profileNameArg = args[1] as String?
            val wrapped: List<Any?> = try {
              listOf(api.setIncludeCookiesOnShouldInterceptRequestEnabled(enabledArg, profileNameArg))
            } catch (exception: Throwable) {
              ServiceWorkerPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ServiceWorkerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ServiceWorkerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ServiceWorkerPigeonCodec()
    }
  }
  /**
   * The app's answer to a Service Worker's request. **Null means "not handled"** and the request
   * goes to the network — measured in §185 (a mutant that decoded every answer as null made the
   * replacement test read `from-server`). So the return type is nullable by necessity, not
   * convenience.
   *
   * `@async` because the app's handler is async; on a FlutterApi that affects only the Dart side.
   */
  fun shouldInterceptRequest(requestArg: WebResourceRequestData, callback: (Result<WebResourceResponseData?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_inappwebview_android.ServiceWorkerFlutterApi.shouldInterceptRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as WebResourceResponseData?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(ServiceWorkerPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
