import 'package:flutter/foundation.dart';
import 'package:flutter_inappwebview_platform_interface/flutter_inappwebview_platform_interface.dart';
import 'package:flutter_test/flutter_test.dart';

/// Guards `onInsertInputSuggestion` and its gate (iOS 26.0+,
/// `WKUIDelegate.webView(_:insertInputSuggestion:)`).
///
/// Two things are worth pinning and neither is obvious from the Dart side.
///
/// **The payload is almost empty, and that is the API, not an omission.** `UIInputSuggestion`
/// declares *no properties at all* — the SDK header says "No properties at this time" — and its only
/// subclass in the whole SDK is `UISmartReplySuggestion`, carrying one `NSString smartReply`. The
/// Swift builds the map by downcasting, so a suggestion that is not a Smart Reply arrives with every
/// field null. A test that asserted a non-null `smartReply` would be asserting something the
/// platform does not promise.
///
/// **The setting is a selector gate, not an event filter.** While `useOnInsertInputSuggestion` is
/// false the plugin's `responds(to:)` override reports that it does not implement the delegate
/// method at all, so WebKit never sees it. That is the §46 mechanism, reused here for a different
/// reason: `runOpenPanelWithParameters` documents its non-implementation behaviour and
/// `insertInputSuggestion` documents none, so hiding the selector is the only way to leave WebKit's
/// own handling untouched for apps that never asked for the event.
///
/// The *event's* own platform table is deliberately not asserted here.
/// `PlatformWebViewCreationParams.isPropertySupported` is an **instance** method, unlike
/// `InAppWebViewSettings.isPropertySupported` a few lines below which is static — trap 25's
/// non-uniformity from a third direction — so checking it needs a constructed creation-params
/// fixture that no test in this repo has. Not worth inventing one for a generated table; the
/// settings gate below is generated by the same emitter and is checked.
void main() {
  group('InputSuggestion', () {
    test('serialises under the key the Swift side emits', () {
      // Swift: `["smartReply": (self as? UISmartReplySuggestion)?.smartReply]`
      expect(
        InputSuggestion(smartReply: 'Sounds good!').toMap()['smartReply'],
        'Sounds good!',
      );
    });

    test('a non-Smart-Reply suggestion decodes to all-null, not to an error', () {
      // What the Swift emits when the downcast fails. The event still fires — the fact that the
      // user picked something is itself the signal — so `fromMap` must accept it.
      final suggestion = InputSuggestion.fromMap({'smartReply': null})!;
      expect(suggestion.smartReply, isNull);
    });

    test('round-trips through fromMap', () {
      final back = InputSuggestion.fromMap(
        InputSuggestion(smartReply: 'On my way').toMap(),
      )!;
      expect(back.smartReply, 'On my way');
    });

    test('carries exactly one field — a change here means Apple added one', () {
      // `UIInputSuggestion` gaining a property, or a second subclass appearing, is the only reason
      // this should ever change. Pinned so that it is a deliberate act rather than drift.
      expect(InputSuggestion(smartReply: 'x').toMap().keys.toSet(), {
        'smartReply',
      });
    });
  });

  group('useOnInsertInputSuggestion', () {
    test('serialises under the key the Swift reads by KVC', () {
      expect(
        InAppWebViewSettings(
          useOnInsertInputSuggestion: true,
        ).toMap()['useOnInsertInputSuggestion'],
        true,
      );
    });

    test('is absent when unset, leaving the Swift default of false', () {
      // Absent rather than false, because `null` is what triggers the automatic inference in
      // `IOSInAppWebView` when the event handler is supplied.
      expect(
        InAppWebViewSettings().toMap()['useOnInsertInputSuggestion'],
        isNull,
      );
    });

    test('is reported iOS-only', () {
      expect(
        InAppWebViewSettings.isPropertySupported(
          InAppWebViewSettingsProperty.useOnInsertInputSuggestion,
          platform: TargetPlatform.iOS,
        ),
        true,
      );
      expect(
        InAppWebViewSettings.isPropertySupported(
          InAppWebViewSettingsProperty.useOnInsertInputSuggestion,
          platform: TargetPlatform.android,
        ),
        false,
      );
    });
  });
}
