// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Everything `ChromeSafariBrowserManager.open` puts into the Custom Tabs Activity's `Bundle`.
class ChromeSafariBrowserOpenRequestData {
  ChromeSafariBrowserOpenRequestData({
    required this.id,
    this.url,
    this.headers,
    this.referrer,
    this.otherLikelyURLs,
    required this.settings,
    this.actionButton,
    this.secondaryToolbar,
    required this.menuItemList,
  });

  /// The browser id: also the suffix of `ChromeCustomTabsHostApi` / `ChromeCustomTabsFlutterApi`.
  String id;

  /// Null opens the tab without a page, for `mayLaunchUrl` / `launchUrl` to use later.
  String? url;

  Map<String?, String?>? headers;

  /// Sent as the Intent's referrer. Chrome replaces it with the app's own (§200).
  String? referrer;

  List<String?>? otherLikelyURLs;

  /// `ChromeSafariBrowserSettings.toMap()`: decision B, a map for the manager's presence reads and
  /// the Activity's `parse(Map)`.
  Map<String?, Object?> settings;

  /// `ChromeSafariBrowserActionButton.toMap()`, icon bytes included.
  Map<String?, Object?>? actionButton;

  /// `ChromeSafariBrowserSecondaryToolbar.toMap()`. A map, which is also what avoids a second
  /// `AndroidResourceData` (checklist item 5).
  Map<String?, Object?>? secondaryToolbar;

  /// Each `ChromeSafariBrowserMenuItem.toMap()`.
  List<Map<String?, Object?>?> menuItemList;

  List<Object?> _toList() {
    return <Object?>[
      id,
      url,
      headers,
      referrer,
      otherLikelyURLs,
      settings,
      actionButton,
      secondaryToolbar,
      menuItemList,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ChromeSafariBrowserOpenRequestData decode(Object result) {
    result as List<Object?>;
    return ChromeSafariBrowserOpenRequestData(
      id: result[0]! as String,
      url: result[1] as String?,
      headers: (result[2] as Map<Object?, Object?>?)?.cast<String?, String?>(),
      referrer: result[3] as String?,
      otherLikelyURLs: (result[4] as List<Object?>?)?.cast<String?>(),
      settings: (result[5]! as Map<Object?, Object?>).cast<String?, Object?>(),
      actionButton: (result[6] as Map<Object?, Object?>?)
          ?.cast<String?, Object?>(),
      secondaryToolbar: (result[7] as Map<Object?, Object?>?)
          ?.cast<String?, Object?>(),
      menuItemList: (result[8]! as List<Object?>)
          .cast<Map<String?, Object?>?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ChromeSafariBrowserOpenRequestData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(url, other.url) &&
        _deepEquals(headers, other.headers) &&
        _deepEquals(referrer, other.referrer) &&
        _deepEquals(otherLikelyURLs, other.otherLikelyURLs) &&
        _deepEquals(settings, other.settings) &&
        _deepEquals(actionButton, other.actionButton) &&
        _deepEquals(secondaryToolbar, other.secondaryToolbar) &&
        _deepEquals(menuItemList, other.menuItemList);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ChromeSafariBrowserOpenRequestData(id: $id, url: $url, headers: $headers, referrer: $referrer, otherLikelyURLs: $otherLikelyURLs, settings: $settings, actionButton: $actionButton, secondaryToolbar: $secondaryToolbar, menuItemList: $menuItemList)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ChromeSafariBrowserOpenRequestData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ChromeSafariBrowserOpenRequestData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Implemented by `ChromeSafariBrowserManager`.
class ChromeSafariBrowserManagerHostApi {
  /// Constructor for [ChromeSafariBrowserManagerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ChromeSafariBrowserManagerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts the Custom Tabs Activity. `false` when there is no host Activity; throws when Custom
  /// Tabs are not available.
  Future<bool> open(ChromeSafariBrowserOpenRequestData request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeSafariBrowserManagerHostApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// `false` when there is no host Activity.
  Future<bool> isAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeSafariBrowserManagerHostApi.isAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// `CustomTabsIntent.getMaxToolbarItems()`.
  Future<int> getMaxToolbarItems() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeSafariBrowserManagerHostApi.getMaxToolbarItems$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// `CustomTabsClient.getPackageName`. Null when there is no host Activity.
  Future<String?> getPackageName(
    List<String>? packages,
    bool ignoreDefault,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeSafariBrowserManagerHostApi.getPackageName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[packages, ignoreDefault],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }
}
