// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// An Android resource reference, mirroring the public `AndroidResource`.
///
/// See checklist item 5: this type is shared with `InAppBrowserMenuItem` and
/// `ChromeCustomTabsSettings`, so the name is expected to collide when `InAppBrowserManager`
/// migrates. That is recorded rather than worked around.
class AndroidResourceData {
  AndroidResourceData({required this.name, this.defType, this.defPackage});

  String name;

  String? defType;

  String? defPackage;

  List<Object?> _toList() {
    return <Object?>[name, defType, defPackage];
  }

  Object encode() {
    return _toList();
  }

  static AndroidResourceData decode(Object result) {
    result as List<Object?>;
    return AndroidResourceData(
      name: result[0]! as String,
      defType: result[1] as String?,
      defPackage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidResourceData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(defType, other.defType) &&
        _deepEquals(defPackage, other.defPackage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidResourceData(name: $name, defType: $defType, defPackage: $defPackage)';
  }
}

/// The remote-views toolbar shown below a Custom Tab.
///
/// 🚨 **`clickableIDs` is flattened to a plain list of resources, and that is not a shortcut.** The
/// public `ChromeSafariBrowserSecondaryToolbarClickableID` has two fields -- an `id` and an
/// `onClick` handler -- but `onClick` is a Dart closure and has never crossed the wire: its
/// `toMap()` emits `{"id": …}` and nothing else, and the Kotlin reads exactly
/// `clickableIDMap["id"]`. So the wrapper object was a one-key envelope on both sides. Flattening
/// removes it; the Dart side keeps the handlers, which is where they were always kept and where the
/// `onSecondaryItemActionPerform` event dispatches to them by name.
class CustomTabsSecondaryToolbarData {
  CustomTabsSecondaryToolbarData({
    required this.layout,
    required this.clickableIDs,
  });

  AndroidResourceData layout;

  List<AndroidResourceData> clickableIDs;

  List<Object?> _toList() {
    return <Object?>[layout, clickableIDs];
  }

  Object encode() {
    return _toList();
  }

  static CustomTabsSecondaryToolbarData decode(Object result) {
    result as List<Object?>;
    return CustomTabsSecondaryToolbarData(
      layout: result[0]! as AndroidResourceData,
      clickableIDs: (result[1]! as List<Object?>).cast<AndroidResourceData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CustomTabsSecondaryToolbarData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(layout, other.layout) &&
        _deepEquals(clickableIDs, other.clickableIDs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CustomTabsSecondaryToolbarData(layout: $layout, clickableIDs: $clickableIDs)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AndroidResourceData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CustomTabsSecondaryToolbarData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AndroidResourceData.decode(readValue(buffer)!);
      case 130:
        return CustomTabsSecondaryToolbarData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> platform, one channel per Custom Tabs activity instance.
class ChromeCustomTabsHostApi {
  /// Constructor for [ChromeCustomTabsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ChromeCustomTabsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Loads [url] in the already-open Custom Tab.
  ///
  /// Answers `false` when the activity is gone or [url] is null — the hand-written handler required
  /// both and answered `false` otherwise. Preserved.
  Future<bool> launchUrl(
    String url,
    Map<String, String>? headers,
    String? referrer,
    List<String>? otherLikelyURLs,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.launchUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url, headers, referrer, otherLikelyURLs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Asks Chrome to pre-warm [url]. Answers Chrome's own answer, or `false` with no activity.
  Future<bool> mayLaunchUrl(String? url, List<String>? otherLikelyURLs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.mayLaunchUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url, otherLikelyURLs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Replaces the toolbar action button's icon and description.
  ///
  /// [icon] is a `Uint8List` and crosses as raw bytes; the hand-written channel sent the same
  /// `ByteArray` through the standard codec.
  Future<bool> updateActionButton(Uint8List icon, String description) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.updateActionButton$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[icon, description],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Asks Chrome to verify a digital-asset-link relation between this app and [origin].
  ///
  /// 🚨 **The one inbound `int` on this channel, and §162's lint trap is aimed straight at it.**
  /// Pigeon maps Dart `int` to Kotlin `Long`; androidx's
  /// `CustomTabsSession.validateRelationship(@Relation int, Uri, Bundle)` wants an `Int`, and
  /// `@Relation` is an `@IntDef`. §162 found that the obvious `.toInt()` narrowing **compiles
  /// cleanly and fails `lintDebug` with `[WrongConstant]`**, because lint cannot see that a runtime
  /// value is one of the permitted constants. Whether it fires here is measured at the lint gate,
  /// not predicted — §162's own fix (a per-element loop) was specific to a *flag* IntDef and has no
  /// analogue for a single value.
  ///
  /// Answers `false` when there is no session. Note that `true` means only that the request was
  /// *accepted*; the verdict arrives on [ChromeCustomTabsFlutterApi.onRelationshipValidationResult],
  /// and §178 measured that it never arrives for this fork at all — the asset-links file for
  /// `inappwebview.dev` delegates to the upstream package, so the test covering this is skipped.
  Future<bool> validateRelationship(int relation, String origin) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.validateRelationship$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[relation, origin],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Replaces the secondary toolbar. Answers `false` when the activity is gone.
  Future<bool> updateSecondaryToolbar(
    CustomTabsSecondaryToolbarData secondaryToolbar,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.updateSecondaryToolbar$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[secondaryToolbar],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Asks Chrome to open a post-message channel from [sourceOrigin].
  ///
  /// 🚨 **`true` here does not mean a channel exists** — it means the request was accepted.
  /// [ChromeCustomTabsFlutterApi.onMessageChannelReady] is what says a channel is open, and Chrome
  /// only fires it after verifying digital asset links. §178 measured the gap: this method answered
  /// `true` and `onMessageChannelReady` never fired, hanging its test for a full 60 seconds.
  ///
  /// **That test is now skipped**, so this method and [postMessage] have *no* device coverage — see
  /// the Residue note in §178. Do not read a green `chrome_safari_browser` run as covering them.
  Future<bool> requestPostMessageChannel(
    String sourceOrigin,
    String? targetOrigin,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.requestPostMessageChannel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sourceOrigin, targetOrigin],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Posts a message through an open channel.
  ///
  /// Answers `CustomTabsService`'s own result code, and **`RESULT_FAILURE_MESSAGING_ERROR` when
  /// there is no session** — a value, not a `false`, which is why this returns `int` rather than
  /// `bool`. Preserved exactly; the Dart side maps it to `CustomTabsPostMessageResultType`.
  Future<int> postMessage(String message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.postMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Whether Chrome will deliver engagement signals for this session.
  ///
  /// The hand-written handler wrapped this in `try`/`catch (Throwable)` answering `false`, because
  /// the androidx call throws on builds that do not implement it. Preserved rather than allowed to
  /// propagate: turning "unsupported" into a `PlatformException` would be a behaviour change.
  Future<bool> isEngagementSignalsApiAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.isEngagementSignalsApiAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Closes the Custom Tab and brings the host activity back. Answers `false` when already gone.
  Future<bool> close() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsHostApi.close$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Platform -> Dart, on the same per-instance channel.
///
/// 🚨 **Eleven of these thirteen names collide with the public API, so none of them can be
/// implemented directly on the controller.** `PlatformChromeSafariBrowserEvents` declares
/// `onServiceConnected`, `onOpened`, `onNavigationEvent` and the rest as **methods with domain
/// types** — `onNavigationEvent(CustomTabsNavigationEventType?)`, not `onNavigationEvent(int)` — and
/// users override them. A class cannot both inherit those and implement the generated ones.
///
/// So the events go through a private forwarder that converts each wire value into its domain type
/// before calling the public method, exactly as §14 did for `onFindResultReceived` and §177 for
/// `onComplete`. This is the third time P0a item 4's prediction has landed, and the largest: it is
/// the difference between a schema that compiles and one that does not.
///
/// Note also checklist item 7: a `messageChannelSuffix` mismatch on *this* direction fails
/// **silently** (§177 measured the asymmetry), and thirteen events is a lot of silence.
abstract class ChromeCustomTabsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onServiceConnected();

  void onOpened();

  /// 🚨 **Takes no argument, although the public callback does.**
  /// `PlatformChromeSafariBrowserEvents.onCompletedInitialLoad(bool? didLoadSuccessfully)` is read
  /// from `call.arguments["didLoadSuccessfully"]` today — and the Kotlin sends
  /// `hashMapOf<String, Any?>()`, an **empty map**. So the value has always been null on Android; it
  /// is an iOS-supplied field on a shared callback.
  ///
  /// Modelling it would put a permanently-null argument on the wire, which is §160's finding
  /// recreated. The forwarder passes `null` explicitly instead, which is exactly what an absent key
  /// already produced — the same call §177 made for `PrintJobInfo`'s fourteen.
  void onCompletedInitialLoad();

  /// `int` on the wire, `CustomTabsNavigationEventType?` in the public callback — the conversion is
  /// the forwarder's job and is the reason the forwarder exists.
  void onNavigationEvent(int navigationEvent);

  void onClosed();

  /// The action button's id, plus the page it was pressed on.
  ///
  /// [url] and [title] are nullable because the Kotlin signature is
  /// `onItemActionPerform(id: Int, url: String?, title: String?)`. Note the Dart side reads them as
  /// **non-null** today (`String url = call.arguments["url"]`), so a null has always been an
  /// implicit-cast crash rather than a handled case. The forwarder preserves that rather than
  /// quietly fixing it — a null here is a platform contract question, not a transport one.
  void onItemActionPerform(int id, String? url, String? title);

  /// [name] is the resource *name* of the secondary-toolbar view that was clicked; the Dart side
  /// matches it against the `clickableIDs` it registered and calls that entry's `onClick`.
  void onSecondaryItemActionPerform(String? name, String? url);

  /// The verdict [ChromeCustomTabsHostApi.validateRelationship] asked for. Never fires in this fork
  /// — see that method.
  void onRelationshipValidationResult(
    int relation,
    String requestedOrigin,
    bool result,
  );

  /// Fires only after Chrome has verified asset links; see
  /// [ChromeCustomTabsHostApi.requestPostMessageChannel].
  void onMessageChannelReady();

  void onPostMessage(String message);

  void onVerticalScrollEvent(bool isDirectionUp);

  void onGreatestScrollPercentageIncreased(int scrollPercentage);

  void onSessionEnded(bool didUserInteract);

  static void setUp(
    ChromeCustomTabsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onServiceConnected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onServiceConnected();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onOpened$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onOpened();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onCompletedInitialLoad$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCompletedInitialLoad();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onNavigationEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_navigationEvent = args[0]! as int;
          try {
            api.onNavigationEvent(arg_navigationEvent);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onClosed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onClosed();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onItemActionPerform$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_id = args[0]! as int;
          final String? arg_url = args[1] as String?;
          final String? arg_title = args[2] as String?;
          try {
            api.onItemActionPerform(arg_id, arg_url, arg_title);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onSecondaryItemActionPerform$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_name = args[0] as String?;
          final String? arg_url = args[1] as String?;
          try {
            api.onSecondaryItemActionPerform(arg_name, arg_url);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onRelationshipValidationResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_relation = args[0]! as int;
          final String arg_requestedOrigin = args[1]! as String;
          final bool arg_result = args[2]! as bool;
          try {
            api.onRelationshipValidationResult(
              arg_relation,
              arg_requestedOrigin,
              arg_result,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onMessageChannelReady$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onMessageChannelReady();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onPostMessage$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_message = args[0]! as String;
          try {
            api.onPostMessage(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onVerticalScrollEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_isDirectionUp = args[0]! as bool;
          try {
            api.onVerticalScrollEvent(arg_isDirectionUp);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onGreatestScrollPercentageIncreased$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_scrollPercentage = args[0]! as int;
          try {
            api.onGreatestScrollPercentageIncreased(arg_scrollPercentage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.ChromeCustomTabsFlutterApi.onSessionEnded$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_didUserInteract = args[0]! as bool;
          try {
            api.onSessionEnded(arg_didUserInteract);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
