// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GeolocationPermissionsHostApi {
  /// Constructor for [GeolocationPermissionsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GeolocationPermissionsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Stores a decision allowing [origin] to use the Geolocation API.
  ///
  /// Answers `false` when the store could not be resolved — `MULTI_PROFILE` unsupported, or no
  /// profile of that name — in which case **nothing was stored**. It never falls back to the default
  /// store: granting an origin location access in the wrong profile is a privacy decision applied to
  /// the wrong session.
  ///
  /// Synchronous: `GeolocationPermissions.allow` returns `void` and the `true` is this plugin's
  /// "the store was resolved and the call was made".
  Future<bool> allow(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.GeolocationPermissionsHostApi.allow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Removes any stored decision for [origin], so the next request from it prompts again.
  ///
  /// Clearing is not denying: there is no stored "deny". Answers `false` on an unresolvable store;
  /// see [allow].
  Future<bool> clear(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.GeolocationPermissionsHostApi.clear$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Removes every stored decision. Answers `false` on an unresolvable store; see [allow].
  Future<bool> clearAll(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.GeolocationPermissionsHostApi.clearAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Whether [origin] has a stored decision allowing the Geolocation API.
  ///
  /// 🚨 **`bool?`, and the null is load-bearing — it is the only such null on this channel.** Null
  /// means the question *could not be asked* (unresolvable store); `false` means it was asked and
  /// nothing is stored. Collapsing them would report "no decision" for a profile that was never
  /// consulted, and a caller deciding whether to prompt on that basis would prompt wrongly.
  ///
  /// This is the branch the migration most had to preserve, and the one the four other methods
  /// deliberately disagree with: they answer `false` (or an empty list) for the same condition.
  /// Pigeon makes an unanswered branch unrepresentable, so each is restated by hand in the Kotlin.
  /// §174's `an unknown profile resolves to no store` pins all five on a device.
  ///
  /// `@async`: `GeolocationPermissions.getAllowed` reports through a `ValueCallback<Boolean>`.
  Future<bool?> getAllowed(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.GeolocationPermissionsHostApi.getAllowed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as bool?;
  }

  /// The origins that have a stored decision allowing the Geolocation API.
  ///
  /// 🚨 **These come back normalised, with a trailing `/`** — `allow("https://x.test")` is listed
  /// here as `"https://x.test/"`. Measured in §174, where it failed four tests at once and looked
  /// like four problems. The other four methods accept **either** form, so listing then acting
  /// works; only comparing against the string you passed to [allow] does not. The public dartdoc on
  /// `getOrigins` and `allow` now says so.
  ///
  /// Answers an empty list on an unresolvable store — which is a *third* spelling of the same
  /// condition, alongside [allow]'s `false` and [getAllowed]'s `null`. Preserved as-is rather than
  /// harmonised; harmonising is a platform-interface change.
  ///
  /// `@async`: `GeolocationPermissions.getOrigins` reports through a `ValueCallback<Set<String>>`.
  /// The platform's `Set` has no wire representation, so the Kotlin copies it into a list — order is
  /// therefore whatever the set iterates, and nothing should depend on it.
  Future<List<String>> getOrigins(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.GeolocationPermissionsHostApi.getOrigins$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}
