// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Everything `InAppBrowserManager.open` puts into the browser Activity's `Bundle`.
///
/// Exactly one of [urlRequest], [assetFilePath] and [data] is set, by `openUrlRequest`, `openFile`
/// and `openData` respectively.
class InAppBrowserOpenRequestData {
  InAppBrowserOpenRequestData({
    required this.id,
    this.urlRequest,
    this.assetFilePath,
    this.data,
    this.mimeType,
    this.encoding,
    this.baseUrl,
    this.historyUrl,
    required this.settings,
    required this.contextMenu,
    this.windowId,
    required this.initialUserScripts,
    required this.pullToRefreshSettings,
    required this.menuItems,
  });

  /// The browser id: also the suffix of `InAppBrowserHostApi` / `InAppBrowserFlutterApi` (§195).
  String id;

  /// `URLRequest.toMap()`, passed through as a map. It goes into the Bundle as `Serializable`.
  Map<String?, Object?>? urlRequest;

  String? assetFilePath;

  String? data;

  String? mimeType;

  /// Handed to `loadDataWithBaseURL`, which ignores it on API 37 (§196).
  String? encoding;

  String? baseUrl;

  String? historyUrl;

  /// `InAppBrowserClassSettings.toMap()`: decision B, a map for the Activity's `parse(Map)`.
  Map<String?, Object?> settings;

  /// `ContextMenu.toMap()`, or an empty map when there is none, as before.
  Map<String?, Object?> contextMenu;

  /// Null when the browser was not opened for a window a page asked for. Kotlin stores it with
  /// `putInt`, so it is narrowed there (checklist item 4).
  int? windowId;

  List<Map<String?, Object?>?> initialUserScripts;

  Map<String?, Object?> pullToRefreshSettings;

  /// Each `InAppBrowserMenuItem.toMap()`. A map, which is also what avoids the
  /// `AndroidResourceData` collision (checklist item 5).
  List<Map<String?, Object?>?> menuItems;

  List<Object?> _toList() {
    return <Object?>[
      id,
      urlRequest,
      assetFilePath,
      data,
      mimeType,
      encoding,
      baseUrl,
      historyUrl,
      settings,
      contextMenu,
      windowId,
      initialUserScripts,
      pullToRefreshSettings,
      menuItems,
    ];
  }

  Object encode() {
    return _toList();
  }

  static InAppBrowserOpenRequestData decode(Object result) {
    result as List<Object?>;
    return InAppBrowserOpenRequestData(
      id: result[0]! as String,
      urlRequest: (result[1] as Map<Object?, Object?>?)
          ?.cast<String?, Object?>(),
      assetFilePath: result[2] as String?,
      data: result[3] as String?,
      mimeType: result[4] as String?,
      encoding: result[5] as String?,
      baseUrl: result[6] as String?,
      historyUrl: result[7] as String?,
      settings: (result[8]! as Map<Object?, Object?>).cast<String?, Object?>(),
      contextMenu: (result[9]! as Map<Object?, Object?>)
          .cast<String?, Object?>(),
      windowId: result[10] as int?,
      initialUserScripts: (result[11]! as List<Object?>)
          .cast<Map<String?, Object?>?>(),
      pullToRefreshSettings: (result[12]! as Map<Object?, Object?>)
          .cast<String?, Object?>(),
      menuItems: (result[13]! as List<Object?>).cast<Map<String?, Object?>?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InAppBrowserOpenRequestData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(urlRequest, other.urlRequest) &&
        _deepEquals(assetFilePath, other.assetFilePath) &&
        _deepEquals(data, other.data) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(encoding, other.encoding) &&
        _deepEquals(baseUrl, other.baseUrl) &&
        _deepEquals(historyUrl, other.historyUrl) &&
        _deepEquals(settings, other.settings) &&
        _deepEquals(contextMenu, other.contextMenu) &&
        _deepEquals(windowId, other.windowId) &&
        _deepEquals(initialUserScripts, other.initialUserScripts) &&
        _deepEquals(pullToRefreshSettings, other.pullToRefreshSettings) &&
        _deepEquals(menuItems, other.menuItems);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InAppBrowserOpenRequestData(id: $id, urlRequest: $urlRequest, assetFilePath: $assetFilePath, data: $data, mimeType: $mimeType, encoding: $encoding, baseUrl: $baseUrl, historyUrl: $historyUrl, settings: $settings, contextMenu: $contextMenu, windowId: $windowId, initialUserScripts: $initialUserScripts, pullToRefreshSettings: $pullToRefreshSettings, menuItems: $menuItems)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is InAppBrowserOpenRequestData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return InAppBrowserOpenRequestData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Implemented by `InAppBrowserManager`.
class InAppBrowserManagerHostApi {
  /// Constructor for [InAppBrowserManagerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  InAppBrowserManagerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts the browser Activity. `false` when there is no host Activity to start it from.
  Future<bool> open(InAppBrowserOpenRequestData request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.InAppBrowserManagerHostApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Opens [url] in another app. `false` when there is no host Activity; throws when no app can
  /// open it.
  Future<bool> openWithSystemBrowser(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.InAppBrowserManagerHostApi.openWithSystemBrowser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
