// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One print job's state, mirroring the platform interface's `PrintJobInfo` **as far as Android
/// populates it**.
///
/// 🚨 **Checklist item 9, in the opposite direction to every previous migration.** §160 found seven
/// fields per proxy rule that the wire carried and the platform never read; §163 nine per
/// credential; §168 one always-null `isSessionOnly`. Here the wire carries nothing dead — instead
/// the **reader expects fourteen fields the wire has never carried**:
///
///  * `PrintJobInfo.fromMap` reads 15 keys; the Kotlin `toMap()` sends **7**. The missing eight —
///    `canSpawnSeparateThread`, `currentPage`, `firstPage`, `isCopyingOperation`, `lastPage`,
///    `preferredRenderingQuality`, `showsPrintPanel`, `showsProgressPanel` — have **zero
///    occurrences in the entire Android Kotlin module**, measured by grep per key.
///  * `PrintJobAttributes.fromMap` reads 12; the Kotlin sends **6**. The missing six are
///    `footerHeight`, `headerHeight`, `maximumContentHeight`, `maximumContentWidth`, `paperRect`
///    and `printableRect`, all likewise absent from the Android source.
///
/// They are iOS-only fields on a shared cross-platform type, and today they arrive as *absent map
/// keys*, which `fromMap` reads as null. So modelling only what Android sends is **exactly
/// behaviour-preserving** — the Dart side passes null for the rest when rebuilding the public type,
/// which is what an absent key already produced. It is also the §168 precedent (drop what is always
/// null) applied to the only case where the alternative was to invent 14 permanently-null wire
/// fields. §176's device test pins all eight of the `PrintJobInfo` ones as null so that a change in
/// either direction is visible.
class PrintJobInfoData {
  PrintJobInfoData({
    required this.state,
    required this.copies,
    this.numberOfPages,
    required this.creationTime,
    required this.label,
    this.printerId,
    this.attributes,
  });

  /// `android.print.PrintJobInfo`'s own constant, rebuilt into `PrintJobState` on the Dart side.
  int state;

  int copies;

  /// `info.pages?.size` — null when the job does not describe a page range, which is the common
  /// case for a job that has only just been created.
  int? numberOfPages;

  /// Epoch milliseconds. Already a Kotlin `Long`, so this is the one number here that needs no
  /// widening (checklist item 4).
  int creationTime;

  String label;

  /// 🚨 **Flattened from a nested one-key map, deliberately.** The hand-written Kotlin sent
  /// `"printer" to hashMapOf("id" to printerId)` and the public `Printer` type has exactly one
  /// field, `id`. The nesting bought nothing.
  ///
  /// Note the Dart side must still build a **non-null** `Printer` when this is null: the old map was
  /// always present even when the id inside it was null, so `Printer.fromMap` always returned an
  /// object. Rebuilding it as `Printer(id: printerId)` unconditionally preserves that; making the
  /// `Printer` itself null when the id is null would be a behaviour change dressed up as a tidy-up.
  String? printerId;

  PrintJobAttributesData? attributes;

  List<Object?> _toList() {
    return <Object?>[
      state,
      copies,
      numberOfPages,
      creationTime,
      label,
      printerId,
      attributes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PrintJobInfoData decode(Object result) {
    result as List<Object?>;
    return PrintJobInfoData(
      state: result[0]! as int,
      copies: result[1]! as int,
      numberOfPages: result[2] as int?,
      creationTime: result[3]! as int,
      label: result[4]! as String,
      printerId: result[5] as String?,
      attributes: result[6] as PrintJobAttributesData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobInfoData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) &&
        _deepEquals(copies, other.copies) &&
        _deepEquals(numberOfPages, other.numberOfPages) &&
        _deepEquals(creationTime, other.creationTime) &&
        _deepEquals(label, other.label) &&
        _deepEquals(printerId, other.printerId) &&
        _deepEquals(attributes, other.attributes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobInfoData(state: $state, copies: $copies, numberOfPages: $numberOfPages, creationTime: $creationTime, label: $label, printerId: $printerId, attributes: $attributes)';
  }
}

/// The job's print attributes, again only as far as Android populates them; see [PrintJobInfoData].
class PrintJobAttributesData {
  PrintJobAttributesData({
    required this.colorMode,
    this.duplex,
    this.orientation,
    this.mediaSize,
    this.resolution,
    this.margins,
  });

  int colorMode;

  int? duplex;

  /// **Derived, not read.** `PrintAttributes` has no orientation; the Kotlin computes it as
  /// `if (mediaSize.isPortrait) 0 else 1` and leaves it null when there is no media size at all.
  /// Preserved as-is.
  int? orientation;

  PrintJobMediaSizeData? mediaSize;

  PrintJobResolutionData? resolution;

  PrintJobMarginsData? margins;

  List<Object?> _toList() {
    return <Object?>[
      colorMode,
      duplex,
      orientation,
      mediaSize,
      resolution,
      margins,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PrintJobAttributesData decode(Object result) {
    result as List<Object?>;
    return PrintJobAttributesData(
      colorMode: result[0]! as int,
      duplex: result[1] as int?,
      orientation: result[2] as int?,
      mediaSize: result[3] as PrintJobMediaSizeData?,
      resolution: result[4] as PrintJobResolutionData?,
      margins: result[5] as PrintJobMarginsData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobAttributesData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorMode, other.colorMode) &&
        _deepEquals(duplex, other.duplex) &&
        _deepEquals(orientation, other.orientation) &&
        _deepEquals(mediaSize, other.mediaSize) &&
        _deepEquals(resolution, other.resolution) &&
        _deepEquals(margins, other.margins);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobAttributesData(colorMode: $colorMode, duplex: $duplex, orientation: $orientation, mediaSize: $mediaSize, resolution: $resolution, margins: $margins)';
  }
}

/// Matches the public `PrintJobMediaSize` field for field, in both directions — one of the three
/// leaf types on this channel where nothing is added and nothing is dropped.
class PrintJobMediaSizeData {
  PrintJobMediaSizeData({
    required this.id,
    this.label,
    required this.widthMils,
    required this.heightMils,
  });

  String id;

  String? label;

  int widthMils;

  int heightMils;

  List<Object?> _toList() {
    return <Object?>[id, label, widthMils, heightMils];
  }

  Object encode() {
    return _toList();
  }

  static PrintJobMediaSizeData decode(Object result) {
    result as List<Object?>;
    return PrintJobMediaSizeData(
      id: result[0]! as String,
      label: result[1] as String?,
      widthMils: result[2]! as int,
      heightMils: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobMediaSizeData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(widthMils, other.widthMils) &&
        _deepEquals(heightMils, other.heightMils);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobMediaSizeData(id: $id, label: $label, widthMils: $widthMils, heightMils: $heightMils)';
  }
}

/// Matches the public `PrintJobResolution` field for field; see [PrintJobMediaSizeData].
class PrintJobResolutionData {
  PrintJobResolutionData({
    required this.id,
    required this.label,
    required this.verticalDpi,
    required this.horizontalDpi,
  });

  String id;

  String label;

  int verticalDpi;

  int horizontalDpi;

  List<Object?> _toList() {
    return <Object?>[id, label, verticalDpi, horizontalDpi];
  }

  Object encode() {
    return _toList();
  }

  static PrintJobResolutionData decode(Object result) {
    result as List<Object?>;
    return PrintJobResolutionData(
      id: result[0]! as String,
      label: result[1]! as String,
      verticalDpi: result[2]! as int,
      horizontalDpi: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobResolutionData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(verticalDpi, other.verticalDpi) &&
        _deepEquals(horizontalDpi, other.horizontalDpi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobResolutionData(id: $id, label: $label, verticalDpi: $verticalDpi, horizontalDpi: $horizontalDpi)';
  }
}

/// The job's minimum margins, rebuilt into Flutter's `EdgeInsets` on the Dart side.
///
/// `double`, not `int`: these are the only non-integer numbers on the channel, and they are already
/// `Double` in the Kotlin, so no conversion happens in either direction.
class PrintJobMarginsData {
  PrintJobMarginsData({
    required this.top,
    required this.right,
    required this.bottom,
    required this.left,
  });

  double top;

  double right;

  double bottom;

  double left;

  List<Object?> _toList() {
    return <Object?>[top, right, bottom, left];
  }

  Object encode() {
    return _toList();
  }

  static PrintJobMarginsData decode(Object result) {
    result as List<Object?>;
    return PrintJobMarginsData(
      top: result[0]! as double,
      right: result[1]! as double,
      bottom: result[2]! as double,
      left: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobMarginsData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(top, other.top) &&
        _deepEquals(right, other.right) &&
        _deepEquals(bottom, other.bottom) &&
        _deepEquals(left, other.left);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobMarginsData(top: $top, right: $right, bottom: $bottom, left: $left)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PrintJobInfoData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PrintJobAttributesData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PrintJobMediaSizeData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PrintJobResolutionData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PrintJobMarginsData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PrintJobInfoData.decode(readValue(buffer)!);
      case 130:
        return PrintJobAttributesData.decode(readValue(buffer)!);
      case 131:
        return PrintJobMediaSizeData.decode(readValue(buffer)!);
      case 132:
        return PrintJobResolutionData.decode(readValue(buffer)!);
      case 133:
        return PrintJobMarginsData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> platform, one channel per `PrintJobController` instance.
///
/// The `messageChannelSuffix` is the job id, so the two halves must agree on it exactly; §165 proved
/// that a mismatch here produces no error at all, just a call that never arrives and a 60-second
/// timeout.
class PrintJobControllerHostApi {
  /// Constructor for [PrintJobControllerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PrintJobControllerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Cancels the job.
  ///
  /// Answers `false` only when the controller has already been disposed. **It does not mean the job
  /// was cancelled** — `android.print.PrintJob.cancel()` is a no-op while the job is in `CREATED`
  /// state, which is the state it is in for as long as the print dialog is open. Measured in §176,
  /// where `getInfo().state` stays `CREATED` across a `cancel()`; the pre-existing behaviour is
  /// preserved rather than corrected, because correcting it means waiting on a job state no test can
  /// reach.
  Future<bool> cancel() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.PrintJobControllerHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Restarts the job. Answers `false` only when the controller has been disposed.
  ///
  /// Like [cancel], a no-op against the only state a test can produce: `PrintJob.restart()` applies
  /// to a **failed** job. Preserved as-is.
  Future<bool> restart() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.PrintJobControllerHostApi.restart$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// The job's current state, or null when the controller has been disposed or holds no job.
  ///
  /// Null is the only signal this channel gives that a controller is finished — §176 asserts
  /// `getInfo()` answers null after [dispose], which is that group's one true state transition.
  Future<PrintJobInfoData?> getInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.PrintJobControllerHostApi.getInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PrintJobInfoData?;
  }

  /// Releases the native controller and cancels the underlying job.
  ///
  /// Answers `false` only when it had already been disposed. Note the **facade** drops this answer
  /// twice over: `PlatformPrintJobController.dispose()` is `Future<void>`, and the app-facing
  /// `PrintJobController.dispose()` is plain `void`, so a caller can neither read the result nor
  /// await the teardown. Recorded, not changed — both are public signatures.
  Future<bool> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.PrintJobControllerHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Platform -> Dart, on the same per-instance channel.
///
/// 🚨 **This is §14's predicted name collision, arriving for the first time.** P0a item 4 has
/// carried the line *"Expect a private forwarding class per event whose name collides with a
/// platform-interface member"* since the pilot. `PlatformPrintJobController` exposes
/// `PrintJobCompletionHandler? onComplete` as a **field**, and Pigeon generates a **method** of the
/// same name — which Dart rejects as inconsistent inheritance if one class tries to be both.
///
/// So `AndroidPrintJobController` does **not** implement this API directly. A private
/// `_PrintJobControllerFlutterApiImpl` receives the event and forwards it to the controller's
/// callback field, exactly as §14 did for `onFindResultReceived`. §165's two channels escaped this
/// only because `onMessage` and `onPostMessage` happen not to collide with anything.
abstract class PrintJobControllerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Fires when the print job finishes, from `InAppWebViewPrintDocumentAdapter.onFinish()`.
  ///
  /// [error] is always null on Android today — the adapter's callback has no failure path — but it
  /// is kept nullable because the public `PrintJobCompletionHandler` takes it and iOS supplies it.
  void onComplete(bool completed, String? error);

  static void setUp(
    PrintJobControllerFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.PrintJobControllerFlutterApi.onComplete$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_completed = args[0]! as bool;
          final String? arg_error = args[1] as String?;
          try {
            api.onComplete(arg_completed, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
