// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors the platform interface's `ProcessGlobalConfigDirectoryBasePaths`.
///
/// **Both fields are non-null on purpose.** The platform-interface type declares them
/// non-nullable, but the Kotlin side stored them as `String?` and force-unwrapped with `!!` when
/// building the `File`s. That only ever worked because Dart could not send null; typing them
/// `required` here makes the guarantee the Kotlin code was already relying on an explicit part of
/// the wire contract.
class ProcessGlobalConfigDirectoryBasePathsData {
  ProcessGlobalConfigDirectoryBasePathsData({
    required this.dataDirectoryBasePath,
    required this.cacheDirectoryBasePath,
  });

  String dataDirectoryBasePath;

  String cacheDirectoryBasePath;

  List<Object?> _toList() {
    return <Object?>[dataDirectoryBasePath, cacheDirectoryBasePath];
  }

  Object encode() {
    return _toList();
  }

  static ProcessGlobalConfigDirectoryBasePathsData decode(Object result) {
    result as List<Object?>;
    return ProcessGlobalConfigDirectoryBasePathsData(
      dataDirectoryBasePath: result[0]! as String,
      cacheDirectoryBasePath: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessGlobalConfigDirectoryBasePathsData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dataDirectoryBasePath, other.dataDirectoryBasePath) &&
        _deepEquals(cacheDirectoryBasePath, other.cacheDirectoryBasePath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProcessGlobalConfigDirectoryBasePathsData(dataDirectoryBasePath: $dataDirectoryBasePath, cacheDirectoryBasePath: $cacheDirectoryBasePath)';
  }
}

/// Mirrors the platform interface's `ProcessGlobalConfigSettings`.
///
/// Deliberately a separate type, for the same reason as `FindSessionData`: the
/// platform-interface version is the public API, so it cannot be Pigeon-generated without coupling
/// every platform to this schema.
class ProcessGlobalConfigSettingsData {
  ProcessGlobalConfigSettingsData({
    this.dataDirectorySuffix,
    this.directoryBasePaths,
  });

  /// Null means "no suffix", which is not the same as the empty string — androidx rejects an
  /// empty suffix. The hand-written channel expressed this by omitting the map key.
  String? dataDirectorySuffix;

  ProcessGlobalConfigDirectoryBasePathsData? directoryBasePaths;

  List<Object?> _toList() {
    return <Object?>[dataDirectorySuffix, directoryBasePaths];
  }

  Object encode() {
    return _toList();
  }

  static ProcessGlobalConfigSettingsData decode(Object result) {
    result as List<Object?>;
    return ProcessGlobalConfigSettingsData(
      dataDirectorySuffix: result[0] as String?,
      directoryBasePaths:
          result[1] as ProcessGlobalConfigDirectoryBasePathsData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessGlobalConfigSettingsData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dataDirectorySuffix, other.dataDirectorySuffix) &&
        _deepEquals(directoryBasePaths, other.directoryBasePaths);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProcessGlobalConfigSettingsData(dataDirectorySuffix: $dataDirectorySuffix, directoryBasePaths: $directoryBasePaths)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ProcessGlobalConfigDirectoryBasePathsData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ProcessGlobalConfigSettingsData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ProcessGlobalConfigDirectoryBasePathsData.decode(
          readValue(buffer)!,
        );
      case 130:
        return ProcessGlobalConfigSettingsData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ProcessGlobalConfigHostApi {
  /// Constructor for [ProcessGlobalConfigHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ProcessGlobalConfigHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Returns whether the config was applied.
  ///
  /// `false` means there was no activity to apply it against — the settings were silently not
  /// applied. A thrown error means androidx rejected the config (most often: it had already been
  /// applied once in this process, which it permits only once).
  ///
  /// The Dart side **discards this value**, because the platform interface declares
  /// `Future<void> apply(...)`. Keeping the bool on the wire preserves the hand-written channel's
  /// semantics exactly and keeps the no-activity case distinguishable from success for anyone who
  /// later wants to surface it; collapsing it to `void` would throw that away silently.
  Future<bool> apply(ProcessGlobalConfigSettingsData settings) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProcessGlobalConfigHostApi.apply$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[settings],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
