// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One custom request header, mirroring the platform interface's `CustomHeader` and
/// `androidx.webkit.CustomHeader` alike.
///
/// **One type for both directions, deliberately.** The same shape goes in on [addCustomHeader] and
/// comes back out of [getCustomHeaders], so there is exactly one spelling of it on the wire and the
/// compiler enforces that they agree -- §168's reason for a single `CookieToSetData`, applied here
/// before a second spelling could appear rather than after.
class CustomHeaderData {
  CustomHeaderData({
    required this.name,
    required this.value,
    required this.originRules,
  });

  /// Matched **case-insensitively** by the platform. The casing first added is the casing sent.
  String name;

  /// Matched **case-sensitively** by the platform -- the asymmetry with [name] is why
  /// [ProfileStoreHostApi.getCustomHeaders] picks an androidx overload rather than letting Dart
  /// filter the full set.
  String value;

  /// A `Set<String>` on both public sides, a `List<String>` here because the wire has no set.
  /// Never null: a header with no rules is useless but is a real, representable state, and
  /// collapsing empty to null would read as "every origin" (pinned by
  /// `an empty rule set survives rather than becoming null`).
  List<String> originRules;

  List<Object?> _toList() {
    return <Object?>[name, value, originRules];
  }

  Object encode() {
    return _toList();
  }

  static CustomHeaderData decode(Object result) {
    result as List<Object?>;
    return CustomHeaderData(
      name: result[0]! as String,
      value: result[1]! as String,
      originRules: (result[2]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CustomHeaderData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(value, other.value) &&
        _deepEquals(originRules, other.originRules);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CustomHeaderData(name: $name, value: $value, originRules: $originRules)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CustomHeaderData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CustomHeaderData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ProfileStoreHostApi {
  /// Constructor for [ProfileStoreHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ProfileStoreHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Every profile that exists, including the default one.
  ///
  /// Answers an **empty list** when `MULTI_PROFILE` is unsupported, which is indistinguishable from
  /// a device that genuinely has no profiles -- except that it cannot happen, because the default
  /// profile is always listed. So the empty list is unambiguous in practice: it means the feature is
  /// missing. Preserved from the hand-written channel.
  Future<List<String>> getAllProfileNames() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getAllProfileNames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Creates the profile called [name] if needed, answering the name the platform actually gave it.
  ///
  /// 🚨 **`String?`, and the null is load-bearing.** Null means `MULTI_PROFILE` is unsupported and
  /// *nothing was created*; it is not the same as a profile whose name is empty. Collapsing the two
  /// would let a caller hand `""` to `InAppWebViewSettings.profileName` believing it had a profile.
  ///
  /// The name is read back off the returned `Profile` rather than echoing [name], so the reply
  /// reflects what the platform created. That also means the reply is not free of consequence:
  /// creating a profile **loads it into memory for the life of the process**, which is what makes
  /// [deleteProfile] refuse it afterwards.
  Future<String?> getOrCreateProfile(String name) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getOrCreateProfile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[name],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Deletes the profile called [name].
  ///
  /// Answers `false` for "no such profile" and for "`MULTI_PROFILE` unsupported". It **throws** for
  /// the two refusals, and that is the interesting part of this method.
  ///
  /// 🚨 **The Kotlin must throw `FlutterError("ProfileStoreManager", …)`, not let androidx's
  /// exception propagate.** androidx raises two different classes -- `IllegalStateException` when a
  /// living WebView holds the profile or the profile was loaded this run, `IllegalArgumentException`
  /// when the name is the default profile -- and Pigeon's `wrapError` derives
  /// `PlatformException.code` from `javaClass.simpleName` for anything that is not a `FlutterError`.
  /// Letting them propagate would therefore replace one stable code with two exception-class names.
  ///
  /// That code is not incidental: §171 leaned on `PlatformException(code: "ProfileStoreManager",
  /// "Cannot delete in-use profile")` as its example of a *clean* platform error, in contrast to the
  /// `channel-error` a dead handler produces. `profile_store_delete.dart` pins it on a device, with
  /// both refusals asserted so that the normalisation is observable rather than implied -- a single
  /// refusal would report `"IllegalStateException"` under the broken version and look like a rename.
  ///
  /// Not `@async` despite throwing: see checklist item 2. Pigeon's synchronous wrapper is precisely
  /// what carries the `FlutterError` into the error envelope.
  Future<bool> deleteProfile(String name) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.deleteProfile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[name],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Adds [header] to the profile named [profileName], or to the default profile when it is null.
  ///
  /// 🚨 **`void`, where the old channel answered a constant `true`.** The hand-written handler ran
  /// `customHeaderProfile(call)?.addCustomHeader(...)` and then replied `true` unconditionally --
  /// including when `CUSTOM_REQUEST_HEADERS` was missing, and when the named profile did not exist,
  /// in which case the elvis swallowed the call and nothing was added. The Dart side declares
  /// `Future<void>` and discarded that `true` anyway, so dropping it changes nothing observable and
  /// stops the wire carrying a value that never meant anything.
  ///
  /// This is the mirror image of §169's finding on `web_storage_manager`, where the host computed a
  /// meaningful answer that Dart threw away. Here the host threw away the meaning and Dart was
  /// discarding the husk. Making it honestly answerable is a platform-interface change (`Future<bool>`
  /// on five methods), not a transport one, and is filed rather than done here.
  Future<void> addCustomHeader(
    CustomHeaderData header,
    String? profileName,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.addCustomHeader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[header, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Whether the profile carries any header called [headerName], matched case-insensitively.
  ///
  /// `bool`, not `bool?`: `false` here collapses "no such header" with "the profile or the feature
  /// could not be resolved". That collapse predates this migration -- the Kotlin had `?: false` and
  /// the Dart `?? false` -- and is preserved rather than fixed, because widening it is a change to
  /// `PlatformProfileStore.hasCustomHeader`'s declared `Future<bool>`. Contrast `hasCookies` in
  /// `cookie_manager.dart`, where §168 *did* have a `bool?` to preserve.
  Future<bool> hasCustomHeader(String headerName, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.hasCustomHeader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[headerName, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// The profile's headers, optionally filtered.
  ///
  /// The three androidx overloads collapse into one method with two optional arguments, and **the
  /// Kotlin picks the overload** -- it does not filter a full set in Dart. That is not a style
  /// preference: androidx matches [CustomHeaderData.name] case-insensitively and
  /// [CustomHeaderData.value] case-sensitively, so a Dart-side `where` would get the mixed-case
  /// cases wrong. A null [headerName] selects the unfiltered overload; a non-null [headerName] with
  /// a null [headerValue] selects the name-only one.
  ///
  /// Answers an empty list when the profile or the feature could not be resolved.
  Future<List<CustomHeaderData>> getCustomHeaders(
    String? headerName,
    String? headerValue,
    String? profileName,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.getCustomHeaders$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[headerName, headerValue, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<CustomHeaderData>();
  }

  /// Removes headers called [headerName] -- every value under that name when [headerValue] is null,
  /// otherwise only the one with that exact value.
  ///
  /// `void`; see [addCustomHeader] for why the old constant `true` is gone.
  Future<void> clearCustomHeader(
    String headerName,
    String? headerValue,
    String? profileName,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.clearCustomHeader$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[headerName, headerValue, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Removes every header from the profile. `void`; see [addCustomHeader].
  Future<void> clearAllCustomHeaders(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.ProfileStoreHostApi.clearAllCustomHeaders$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
