// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One origin's storage figures, mirroring `WebStorage.Origin`.
///
/// **All three fields are non-null here, while the public `WebStorageOrigin` declares all three
/// nullable.** That asymmetry is deliberate and is the honest direction: this type is only ever
/// built by the host from a `WebStorage.Origin` the platform has just handed it, where `origin` is
/// the object's own identifier and `quota`/`usage` are primitive `long`s -- none of the three can
/// be absent. The public type's nullability is a legacy of the untyped map it used to be rebuilt
/// from, and is left alone because changing it is a platform-interface change, not a transport one.
///
/// This is the opposite call from §163's `URLProtectionSpaceData`, and for the opposite reason:
/// there the *public* API could produce a null that a Kotlin `!!` then crashed on, so the wire had
/// to admit it. Here the value only ever travels host → Dart, so the wire records what the platform
/// guarantees rather than what the Dart type happens to allow.
class WebStorageOriginData {
  WebStorageOriginData({
    required this.origin,
    required this.quota,
    required this.usage,
  });

  String origin;

  /// Bytes, for the Web SQL Database API. Dart `int` -> Kotlin `Long`, which is already what
  /// `WebStorage.Origin.getQuota()` returns.
  int quota;

  /// Bytes, across all JavaScript storage APIs. See [quota].
  int usage;

  List<Object?> _toList() {
    return <Object?>[origin, quota, usage];
  }

  Object encode() {
    return _toList();
  }

  static WebStorageOriginData decode(Object result) {
    result as List<Object?>;
    return WebStorageOriginData(
      origin: result[0]! as String,
      quota: result[1]! as int,
      usage: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WebStorageOriginData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(origin, other.origin) &&
        _deepEquals(quota, other.quota) &&
        _deepEquals(usage, other.usage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WebStorageOriginData(origin: $origin, quota: $quota, usage: $usage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is WebStorageOriginData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return WebStorageOriginData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WebStorageManagerHostApi {
  /// Constructor for [WebStorageManagerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebStorageManagerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Every origin currently using storage.
  ///
  /// `@async`: `WebStorage.getOrigins` reports through a `ValueCallback<Map>`.
  ///
  /// Answers an empty list when the storage cannot be resolved, as before — which is
  /// indistinguishable from "no origins are using storage". Preserved rather than fixed, because
  /// the alternative is a nullable return and a public-API change; filed in TODO.
  ///
  /// The migration does remove a genuine wart: the platform signature is literally
  /// `getOrigins(ValueCallback<Map>)` — a **raw** `Map` — so the old Kotlin cast the lambda
  /// `as ValueCallback<Map<Any?, Any?>>` behind a class-level `@Suppress("UNCHECKED_CAST")` and
  /// then cast each value `as WebStorage.Origin`. The cast against the platform stays (it is forced
  /// by `android.jar`), but it is now scoped to this one function and the *outbound* half is typed.
  Future<List<WebStorageOriginData>> getOrigins(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.getOrigins$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<WebStorageOriginData>();
  }

  /// Clears storage for every origin.
  ///
  /// 🚨 **The `bool` is computed and then discarded by Dart**, which declares
  /// `Future<void> deleteAllData(...)`. `false` means the storage could not be resolved — no such
  /// profile, or no `MULTI_PROFILE` — so a caller clearing a named profile's storage currently
  /// cannot tell that nothing happened. That is §137's `flush` finding exactly, one channel later.
  ///
  /// It stays on the wire for the same reason §157/§160/§162/§163 kept theirs: the distinction is
  /// real and free to carry, and surfacing it is a platform-interface change that belongs in its own
  /// commit. Filed in TODO.
  ///
  /// Not `@async`: `WebStorage.deleteAllData()` returns `void` and inline.
  Future<bool> deleteAllData(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.deleteAllData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Clears storage for one origin. See [deleteAllData] for the discarded `bool`.
  ///
  /// [origin] is non-null: the public API requires it. The old handler read
  /// `call.argument("origin")` into a nullable and handed that straight to
  /// `WebStorage.deleteOrigin`, so a dropped key reached the platform as null.
  Future<bool> deleteOrigin(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.deleteOrigin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Clears browsing data for every site.
  ///
  /// `@async`: `WebStorageCompat.deleteBrowsingData` signals completion through a `Runnable`.
  ///
  /// Answers `false` when the storage cannot be resolved **or** when
  /// `WebViewFeature.DELETE_BROWSING_DATA` is unsupported — the feature gate is required rather than
  /// defensive, because the compat call throws `UnsupportedOperationException` without it.
  Future<bool> deleteBrowsingData(String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.deleteBrowsingData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Clears browsing data for one site, answering the domain it actually cleared.
  ///
  /// The answer is not [site]: the platform resolves it to the registrable domain, so
  /// `"www.example.com"` comes back as `"example.com"`. Null means the storage could not be resolved
  /// or the feature is unsupported — note this is the **null** counterpart of
  /// [deleteBrowsingData]'s `false`, an inconsistency that predates the migration and is preserved.
  ///
  /// 🚨 **Fails with `PlatformException(code: "MyWebStorage")` when the site cannot be parsed as a
  /// domain name — and the Kotlin must deliver that through the callback rather than throwing.**
  ///
  /// §169 first wrote this as "the exception propagates to Pigeon's `wrapError`", which is **wrong
  /// for an `@async` method**: the generated handler wraps a *synchronous* host call in
  /// `try { … } catch (Throwable) { wrapError(…) }`, but an `@async` one is a bare
  /// `api.method(args) { result -> … }` with no `try`/`catch`. A synchronous throw escapes the
  /// handler, no reply is sent, and the caller gets `channel-error`. Measured on a device in §170
  /// and fixed there; see the Kotlin.
  ///
  /// The code stays the old `"MyWebStorage"` constant, so this is **not** a breaking change after
  /// all — unlike §165's note, which this paragraph replaces.
  ///
  /// `@async`: completion is signalled through a `Runnable`, and the return value is read *inside*
  /// it — safe only because the compat overload posts to the main looper. See the Kotlin.
  Future<String?> deleteBrowsingDataForSite(
    String site,
    String? profileName,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.deleteBrowsingDataForSite$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[site, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// The Web SQL quota for one origin, in bytes.
  ///
  /// `@async`: `WebStorage.getQuotaForOrigin` reports through a `ValueCallback<Long>`.
  ///
  /// 🚨 **Answers `0` when the storage cannot be resolved**, which is indistinguishable from an
  /// origin that genuinely has a zero quota. Preserved from the hand-written channel — the Dart side
  /// declares `Future<int>` and coalesced a null reply to `0` as well — but recorded because it is
  /// the same collapse `hasCookies` refuses to make (§168). Making it `int?` is a public-API change;
  /// filed in TODO.
  Future<int> getQuotaForOrigin(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.getQuotaForOrigin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Bytes currently used by one origin, across all JavaScript storage APIs.
  ///
  /// `@async`, and answers `0` on an unresolvable store; see [getQuotaForOrigin].
  Future<int> getUsageForOrigin(String origin, String? profileName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebStorageManagerHostApi.getUsageForOrigin$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[origin, profileName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}
