// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors the platform interface's `IWebMessagePort` as it crosses this boundary.
///
/// The Dart `toMap()` sends exactly these two fields, and the Kotlin `WebMessagePortCompatExt`
/// reads exactly these two, so nothing is lost by naming them.
class WebMessagePortData {
  WebMessagePortData({required this.index, required this.webMessageChannelId});

  /// 0 or 1 — which end of the channel. Crosses as a Dart `int`, i.e. Kotlin `Long`, so the
  /// manager narrows it with `.toInt()` (§162).
  int index;

  String webMessageChannelId;

  List<Object?> _toList() {
    return <Object?>[index, webMessageChannelId];
  }

  Object encode() {
    return _toList();
  }

  static WebMessagePortData decode(Object result) {
    result as List<Object?>;
    return WebMessagePortData(
      index: result[0]! as int,
      webMessageChannelId: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WebMessagePortData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) &&
        _deepEquals(webMessageChannelId, other.webMessageChannelId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WebMessagePortData(index: $index, webMessageChannelId: $webMessageChannelId)';
  }
}

/// Mirrors the platform interface's `WebMessage`.
///
/// **The payload is split into two typed fields rather than one `Object?`.** `WebMessage.data` is
/// declared `dynamic` and holds either a `String` or a `Uint8List`, keyed by [type]; the old wire
/// carried it untyped and the Kotlin side recovered it with an unchecked cast:
///
/// ```kotlin
/// port.postMessage(WebMessageCompat(data as ByteArray, ports))   // or data?.toString()
/// ```
///
/// Naming the two shapes separately deletes that cast and lets Pigeon carry the bytes as a real
/// `ByteArray` instead of an `Any?` that happens to be one. Same treatment as §162's category
/// split, and for the same reason: a heterogeneous field is a runtime type test waiting to happen.
///
/// The pairing is **already an invariant of the public type** — `WebMessage`'s constructor asserts
/// that `data` is null-or-`String` exactly when `type` is `STRING`, and a `Uint8List` exactly when
/// it is `ARRAY_BUFFER` — so splitting the field records a rule that already held rather than
/// inventing one.
class WebMessageData {
  WebMessageData({
    required this.type,
    this.stringData,
    this.arrayBufferData,
    this.ports,
  });

  /// `WebMessageType`'s native value: `0` = `STRING`, `1` = `ARRAY_BUFFER`.
  ///
  /// Kept even though [stringData] and [arrayBufferData] are separately typed, because it is the
  /// field the public API carries and it is the only thing that distinguishes a `STRING` message
  /// whose data is **null** from an absent payload. Inferring the type from which field is
  /// non-null would silently change that case.
  ///
  /// Stays an `int` rather than a Pigeon enum, as in §160/§161: the platform interface's
  /// `WebMessageType` is an open `_internal(int)` class, not a closed enum, so a generated enum
  /// would reject values the public API accepts.
  int type;

  /// Set when [type] is `STRING`. Null is legal here and means a `STRING` message with no data,
  /// which androidx forwards as a null `String`.
  String? stringData;

  /// Set when [type] is `ARRAY_BUFFER`. Arrives on the Kotlin side as a real `ByteArray`, so
  /// `WebMessageCompat(ByteArray, …)` needs no cast.
  Uint8List? arrayBufferData;

  /// **Inbound only.** The Kotlin `WebMessageCompatExt.toMap()` omits `ports` entirely, so an
  /// event coming *from* the platform never carries them; only messages Dart posts do. Nullable
  /// rather than a required empty list so that asymmetry stays visible on the type.
  List<WebMessagePortData>? ports;

  List<Object?> _toList() {
    return <Object?>[type, stringData, arrayBufferData, ports];
  }

  Object encode() {
    return _toList();
  }

  static WebMessageData decode(Object result) {
    result as List<Object?>;
    return WebMessageData(
      type: result[0]! as int,
      stringData: result[1] as String?,
      arrayBufferData: result[2] as Uint8List?,
      ports: (result[3] as List<Object?>?)?.cast<WebMessagePortData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WebMessageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(stringData, other.stringData) &&
        _deepEquals(arrayBufferData, other.arrayBufferData) &&
        _deepEquals(ports, other.ports);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WebMessageData(type: $type, stringData: $stringData, arrayBufferData: $arrayBufferData, ports: $ports)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is WebMessagePortData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is WebMessageData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return WebMessagePortData.decode(readValue(buffer)!);
      case 130:
        return WebMessageData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> platform, one channel per `WebMessageChannel` instance via `messageChannelSuffix`.
class WebMessageChannelHostApi {
  /// Constructor for [WebMessageChannelHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebMessageChannelHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Registers the port's message callback, which is what makes
  /// [WebMessageChannelFlutterApi.onMessage] start firing.
  ///
  /// Returns false only when the underlying view is not an `InAppWebView`. Note it answers
  /// **true** when `WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK` is unsupported and nothing was
  /// registered — "true" here means "no error", not "the callback is live". That is the
  /// hand-written channel's behaviour, preserved deliberately; changing it is a separate decision.
  Future<bool> setWebMessageCallback(int index) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageChannelHostApi.setWebMessageCallback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[index],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Posts [message] through the port at [index].
  ///
  /// Same `true`-when-unsupported caveat as [setWebMessageCallback].
  Future<bool> postMessage(int index, WebMessageData message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageChannelHostApi.postMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[index, message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Closes the port at [index]. Same caveat again.
  Future<bool> close(int index) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageChannelHostApi.close$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[index],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Platform -> Dart, on the same per-instance channel.
abstract class WebMessageChannelFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// [message] is nullable because androidx's `WebMessageCallbackCompat.onMessage` may deliver a
  /// null `WebMessageCompat`; the Dart side forwards null to the port's `onMessage` callback.
  void onMessage(int index, WebMessageData? message);

  static void setUp(
    WebMessageChannelFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageChannelFlutterApi.onMessage$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_index = args[0]! as int;
          final WebMessageData? arg_message = args[1] as WebMessageData?;
          try {
            api.onMessage(arg_index, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Dart -> platform, one channel per `WebMessageListener` instance.
class WebMessageListenerHostApi {
  /// Constructor for [WebMessageListenerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebMessageListenerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Posts [message] back through the listener's `JavaScriptReplyProxy`.
  ///
  /// Always answers true when the view is an `InAppWebView`: the hand-written channel called
  /// `result.success(true)` unconditionally at the end, including when there was no reply proxy
  /// or `WEB_MESSAGE_LISTENER` was unsupported. Preserved.
  Future<bool> postMessage(WebMessageData message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageListenerHostApi.postMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Platform -> Dart, on the same per-instance channel.
abstract class WebMessageListenerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPostMessage(
    WebMessageData? message,
    String? sourceOrigin,
    bool isMainFrame,
  );

  static void setUp(
    WebMessageListenerFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_inappwebview_android.WebMessageListenerFlutterApi.onPostMessage$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WebMessageData? arg_message = args[0] as WebMessageData?;
          final String? arg_sourceOrigin = args[1] as String?;
          final bool arg_isMainFrame = args[2]! as bool;
          try {
            api.onPostMessage(arg_message, arg_sourceOrigin, arg_isMainFrame);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
