// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// No data classes: both methods take androidx's own feature string and return a bool.
///
/// The string is `WebViewFeature.toNativeValue()`. It is **not** a Pigeon enum, for the same reason
/// `ProxyRuleData.schemeFilter` is not (§160): the platform interface's `WebViewFeature` is an open
/// `_internal(String)` class rather than a closed enum, and androidx types these parameters as
/// annotated `String`s.
class WebViewFeatureHostApi {
  /// Constructor for [WebViewFeatureHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebViewFeatureHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether androidx supports [feature] on the current platform SDK and WebView version.
  ///
  /// **Throws for a declared-but-unregistered feature.** androidx's `isFeatureSupported` raises
  /// `RuntimeException("Unknown feature ...")` rather than answering `false` for the six
  /// `WebViewFeature` constants that are declared but never registered with
  /// `WebViewFeatureInternal` -- the tombstones §36 found. That behaviour is unchanged by this
  /// migration: the hand-written channel let the exception propagate to Flutter's `MethodChannel`,
  /// which wrapped it, and Pigeon's `wrapError` does the same.
  Future<bool> isFeatureSupported(String feature) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebViewFeatureHostApi.isFeatureSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[feature],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Whether androidx supports [startupFeature], which is a **different** namespace from
  /// [isFeatureSupported] and must not be called with an ordinary feature.
  ///
  /// 🚨 **This fixes a hang.** The hand-written Kotlin read the *activity*
  /// (`plugin?.activity`) and, when it was null, **returned without calling `result` at all** --
  /// no success, no error, no `notImplemented`. `plugin.activity` is genuinely nullable: it is
  /// null until `onAttachedToActivity` and is set back to null on
  /// `onDetachedFromActivityForConfigChanges`, so any call in those windows left the caller's
  /// `await` pending forever. The Dart side's `?? false` could not help -- it defaults a null
  /// *reply*, not a reply that never comes.
  ///
  /// A synchronous Pigeon method has to return a value, which makes that path unrepresentable. The
  /// fix is not "return false": the manager now passes the plugin's **application** context, which
  /// is `lateinit` and always set from `onAttachedToEngine`. That is the correct argument rather
  /// than merely a non-null one -- androidx documents the parameter as "a Context to access
  /// application assets", and `StartupApiFeature` uses it only for `getPackageManager()` and
  /// `WebViewCompat.getCurrentWebViewPackage(context)`, both package-manager lookups an
  /// application context serves identically to an Activity. Verified in the 1.17.0 sources jar,
  /// not inferred from the signature.
  Future<bool> isStartupFeatureSupported(String startupFeature) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_inappwebview_android.WebViewFeatureHostApi.isStartupFeatureSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[startupFeature],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
