package dev.nosferatu500.inappwebview.webview

// The methods still on the hand-written MethodChannel. The rest are Pigeon, on
// `InAppWebViewHostApi` (pigeons/in_app_webview.dart); W1 (§207) moved the 25 synchronous load,
// navigation and state methods, and W2 (§210) the nine that answer from a callback.
enum class WebViewChannelDelegateMethods {
  loadUrl,
  injectJavascriptFileFromUrl,
  injectCSSCode,
  injectCSSFileFromUrl,
  setSettings,
  getSettings,
  getCopyBackForwardList,
  scrollTo,
  scrollBy,
  printCurrentPage,
  zoomBy,
  getZoomScale,
  getHitTestResult,
  pageDown,
  pageUp,
  zoomIn,
  zoomOut,
  requestFocus,
  clearFocus,
  setContextMenu,
  requestFocusNodeHref,
  requestImageRef,
  getScrollX,
  getScrollY,
  getCertificate,
  addUserScript,
  removeUserScript,
  removeUserScriptsByGroupName,
  removeAllUserScripts,
  createWebMessageChannel,
  postWebMessage,
  addWebMessageListener,
  canScrollVertically,
  canScrollHorizontally,
  isInFullscreen,
  hideInputMethod,
  showInputMethod,
  saveState,
  restoreState,
  setAudioMuted,
  isAudioMuted,
  flingScroll,
}
